### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by humroben** [Erigitic/TotalEconomy#1]
I've Installed TotalEconomy onto my Sponge server, but in doing so, the server is prevented from starting, as Forge is unable to Construct the plugin. As it stands, there is only one other plugin, PEX.

From looking at the crash report, the problem exists with TE, and only TE.

I've attached links to the location of the server logs.

https://www.dropbox.com/s/4632p9m92hrx6dw/crash-2015-05-18_11.24.44-server.txt?dl=1
https://www.dropbox.com/s/5zrcz0cv4vrvhr7/latest.log?dl=1

In the Crash Report, and the latest log file, the error is something to do with using unsupported class versions.

NOTE: using Debian Linux, so updating to use Java 8 is a difficult task.

**Comment by Erigitic** [comment]
Looks like you figured it out since the issue is now closed. If not, I will help you out further.

**Comment by humroben** [comment]
It's not solved completely, but has the potential to cause me issues in the future.
Debian has separate channels for builds. These are:

- Stable
- Testing
- Experimental

OpenJDK-8-jre is currently only available from within the experimental channel. This happens to be the latest version java.
Within the Stable channel, the latest java is OpenJDK-7-jre, which is the last version of java 7.

Could I ask that TotalEconomy be built with java 7?

**Comment by Erigitic** [comment]
I am not very familiar with Debian but would it be a bad idea to use the experimental build?

**Comment by humroben** [comment]
The experimental build exists only for the purpose of new packages to be added to the Debian chain. Because its a server, using a non-stable OS is considered a very bad idea. The Testing chain is still too unstable for use as a server, as the last Testing build had been moved over to the stable channel.

I am using the experimental package for java, but I've not been able to use TE, because the plugin crashes, but the server remains operational.

**Comment by Erigitic** [comment]
Would you mind copying and pasting the error log that you get now?

**Comment by humroben** [comment]
http://pastebin.com/sLQaFUkE
http://pastebin.com/X2b6t5RR

Top link is to the error when starting the server, and bottom link is when joining the server.

**Comment by Erigitic** [comment]
The reason for those errors is that you are using a newer version of Sponge that I have yet to update the plugin to. The API changed between 2.0 and 2.1 causing the current code in TE to not work with your version of Sponge. What I should begin doing is writing down the version numbers used when I add a new release. I am updating the plugin to the latest version soon so in the meantime, if you want, you can downgrade to, I believe, version 1.1 of Sponge.

**Comment by Erigitic** [comment]
Ok, just updated to the latest sponge version and was able to reproduce the error. Going to fix it now then add the release.

**Comment by humroben** [comment]
Okie dokie, I had a feeling that updating to the latest sponge could have an impact like that

**Comment by Erigitic** [comment]
Here you go: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.0.1

Hopefully that will work. If not let me know.

**Comment by humroben** [comment]
clean run, thank you :smiley:

**Comment by Erigitic** [comment]
Glad to hear. Sorry for the hassle with Java 8. If you encounter any more issues with TE please feel free to post another issue so I can get it fixed. Have a good one.

**Comment by humroben** [comment]
If I need to, I will. Keep up the good work.
