### ISSUE TITLE
Jobs not recognizes mod items

### ISSUE THREAD

**Issue by jelaw21** [Erigitic/TotalEconomy#101]
I am trying to add jobs support for Forestry copper and tin. The id name is forestry:resources, forestry:resources:1 and forestry:resources:2. However, Jobs is not picking it up. Here is my miner job:

Miner {
    break {
        "coal_ore" {
            expreward="5"
            pay="0.25"
        }
        "diamond_ore" {
            expreward="100"
            pay="25.00"
        }
        "emerald_ore" {
            expreward="50"
            pay="12.50"
        }
        "gold_ore" {
            expreward="40"
            pay="5.00"
        }
        "iron_ore" {
            expreward="10"
            pay="0.50"
        }
        "lapis_ore" {
            expreward="20"
            pay="4.00"
        }
        "quartz_ore" {
            expreward="5"
            pay="0.15"
        }
        "lit_redstone_ore" {
            expreward="25"
            pay="2.00"
        }
        "forestry:resources:1"{
            expreward="5"
            pay=".50"
        }
    }
    disablesalary=false
    permission="totaleconomy.job.miner"
    salary=3
}

**Comment by Erigitic** [comment]
What happens if you just do "resources:1" without the "forestry:" prefix?

**Comment by jelaw21** [comment]
resources without the 1 works. so just "resources"

**Comment by Erigitic** [comment]
Is this fixed then or is something still not working as needed?

**Comment by jelaw21** [comment]
I would say look into it. TCon ores aren't registering, those are
tconstruct:ore  I tried ore and the actual name.

**Comment by Erigitic** [comment]
I have an idea on how to get this working. One more question though. With the TCon ores do they have a number, or anything else, suffixed after it? For example, `tconstruct:ore:1`?

**Comment by jelaw21** [comment]
Yeah. So ore is picking up cobalt but not ardite. Then, I got biomes
working by doing log_0 and so on without the biomes: tag in front. Its just
not intuitive. It would be bettwr if I had to put minecraft:log:* for
vanilla stuff and keel that same tect formatting for mods.

**Comment by MarkL4YG** [comment]
You may want to test the TotalEconomy version [posted by me in this issue(102)](https://github.com/Erigitic/TotalEconomy/issues/102) since it allows you to check what block name is really used. (It logs a message containing the name whenever the BlockPlaceEvent is fired)
Just in case ``tconstruct:ore:<number>`` isn't what's actually returned by ``getName()``

If this is the case: The issue would be resolved.

**Comment by Erigitic** [comment]
@MarkL4YG I believe this will be fixed when issue #105 is resolved.

**Comment by Erigitic** [comment]
Going to close this one as this issue and a few others have been consolidated into issue #105. Please post any more questions relating to this on issue #105. Thanks.
