### ISSUE TITLE
/baltop throwing an error

### ISSUE THREAD

**Issue by Darktilldawn** [Erigitic/TotalEconomy#103]
http://pastebin.com/hE8MwRQe

**Comment by MarkL4YG** [comment]
Thanks for the log, but please provider further information, such as Sponge and TotalEconomy versions.
---
May be related to my last comment on #94

**Comment by Darktilldawn** [comment]
Oh um Total Economy Version 1.5.0 and sponge 1792 for 5.0.0 Mc version 1.10.2

**Comment by toxxicjtag** [comment]
Can also confirm. 
Versions: http://puu.sh/rFFXC/79bc033fc8.jpg
Total eco v1.5.1

**Comment by Erigitic** [comment]
Going to close this issue and ask for you to post on #94 from here on out as it is the same issue.
