### ISSUE TITLE
Getting paid for not doing my job.

### ISSUE THREAD

**Issue by tacogerbil** [Erigitic/TotalEconomy#104]
spongeforge-1.10.2-2092-5.0.0-BETA-1773,forge-1.10.2-12.18.1.2094
I randomly get paid while I'm not doing anything related to the job I chose.  For example I'll be placing stone bricks in a cave, have the lumberjack job and randomly get a message that I was paid.. The salary is turned off and it sometimes happens consecutively.. 5 in a row just seconds apart etc.
No error logs that I can see...

**Comment by Erigitic** [comment]
Send me your main configuration file in a pastebin. Also did you restart your server after disabling the salary?

**Comment by Erigitic** [comment]
@tacogerbil Are you still having this issue?
