### ISSUE TITLE
Get money drop item into lava

### ISSUE THREAD

**Issue by yololetsplay** [Erigitic/TotalEconomy#106]
Hey there :]

Ist it possible to get payed for dropping items into lava?
I created the job "koenig" like king - and on my roleplay server I do it like melting gold ingot pays me 100 coins - like coinage, you know? :]

What I actually have is the following:

Koenig {
    drop {
        gold_ingot {
            expreward="1"
	    pay="100"
        }
    }
    disablesalary=false
    permission="totaleconomy.job.koenig"
    salary=0
}

But it doesn't work if I drop gold ingot.

Would be great if u can help me.

Greetz,
yololetsplay

**Comment by Erigitic** [comment]
There is currently no check in Total Economy for items being dropped which is why it is not working. I feel like this feature would be more appropriate for a custom plugin for your server as I do not see much of a reason to add it to Total Economy. Sorry, but thanks for the suggestion.
