### ISSUE TITLE
Jobs level dependent

### ISSUE THREAD

**Issue by Bloodfreya** [Erigitic/TotalEconomy#107]
This is a 2 parter. First part is for players to be able to unlock new jobs based on current job level. For increased salary. Like a automatic promotion.

Second is for Job level to effect xp and money gained from doing the job related tasks mostly money.

**Comment by MarkL4YG** [comment]
@Erigitic 
Suggestion here:
General "Awards" that let the console run commands + Job restriction via permissions:
This way you could e.g. set a command as permission that grants the player access to another job (``totaleconomy.jobs.miner-l2`` e.g.).
``miner-l1`` could for example reward the permission for ``miner-l2``.

For the second thing:
@Bloodfreya can you specify? I don't really get what you're trying to tell.

**Comment by Bloodfreya** [comment]
Depending on the job you can gain more experience and money for doing that job.

**Comment by Bloodfreya** [comment]
As you can experience for that job you gain nothing. I am currently a 67 miner on a server I am playing, but the money gained is no different from level 1

**Comment by MarkL4YG** [comment]
@Bloodfreya okay, that would be resolved by the same thing as the first one. Technically these two suggestions are somewhat the same.

**Comment by Erigitic** [comment]
Going to leave this one for a later release.

**Comment by MarkL4YG** [comment]
Just wanted to notify @Erigitic that I started working on this.
WIP-PR will follow
