### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by yololetsplay** [Erigitic/TotalEconomy#108]
If you enable permissions=true in config for maybe "totaleconomy.job.farmer" and I add the permission to an user or group using PermissionEx, it says ingame if I try /job set farmer -> "No Permission".

Any idea how to fix this?

Greetz,
yololetsplay

**Comment by MarkL4YG** [comment]
If you take a look [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/jobs/TEJobs.java#L246) the required permission seems to be ``main.job.farmer``

**Comment by yololetsplay** [comment]
Dude that's it! Thx alot! Works great :]

**Comment by MarkL4YG** [comment]
@Erigitic I suggest changing that string ;)

**Comment by Erigitic** [comment]
I changed the permissions to totaleconomy.job.* for 1.5.1 but forgot to change the line of code [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/jobs/TEJobs.java#L246), so thanks for bringing this up. Will get this fixed up today.
