### ISSUE TITLE
Just a Heads Up (Pre-Released Bugs)

### ISSUE THREAD

**Issue by dagaems** [Erigitic/TotalEconomy#11]
http://prntscr.com/899t1p
http://prntscr.com/899t5z
Screenshots says it all (Pre-Release Bugs)

**Comment by Erigitic** [comment]
What version of sponge are you using?

**Comment by dagaems** [comment]
.570 for I wanted to see if it worked on this version. I will try to use the version you used. On a side note, what are the new permissions.

**Comment by Erigitic** [comment]
That is the problem. The plugin is tested with 584. I had the same error but once updated it went away. No new permissions. What permissions would you like?

**Comment by dagaems** [comment]
I would like to be able to set up permissions and have several "unemployed" things in the config. So basic users would get say $6.00 yes but I could make another "unemployed" that gets $9.00

**Comment by Erigitic** [comment]
I do not think I will have it where different ranked players, such as admins or new players, get different salaries. I would like it to be purely based off of the job that player has. What I do plan on doing is allowing the option to increase the salary of players who have a high level in there job.

**Comment by dagaems** [comment]
Any chance you could implement this?
"I would like to be able to set up permissions and have several "unemployed" things in the config. So basic users would get say $6.00 yes but I could make another "unemployed" that gets $9.00"

**Comment by dagaems** [comment]
Where is the .settings to change the balance per time. I can't seem to find it and am getting a crud ton of money atm: https://gyazo.com/21869a9fdb23727daedfe974d111b570

**Comment by Erigitic** [comment]
I will not be implmementing this feature as I want to try and keep it somewhat realistic. To change the time between getting paid you need to change the salarydelay variable in the jobs.conf file. It uses seconds so 300 would equal 5 minutes.

**Comment by dagaems** [comment]
Alright. This can be closed (I'll send ya a message)
