### ISSUE TITLE
Error while booting

### ISSUE THREAD

**Issue by Ashmit7509** [Erigitic/TotalEconomy#111]
26.11 12:19:57 [Server] Sponge Plugin 'totaleconomy' seems to be missing a valid mcmod.info metadata file. This is not a problem when testing plugins, however it is recommended to include one in public plugins.
26.11 12:19:57 [Server] INFO Please see https://docs.spongepowered.org/master/en/plugin/plugin-meta.html for details.
this appears while botting
everything runs fine just wanted to point out nothing else

**Comment by Erigitic** [comment]
I'll get this fixed today. Thanks.

**Comment by Erigitic** [comment]
All fixed. Thanks again.
