### ISSUE TITLE
/baltop giving incorrect balances and order

### ISSUE THREAD

**Issue by DiamondArrow** [Erigitic/TotalEconomy#113]
/balancetop gives incorrect player balances in an incorrect order
![image](https://cloud.githubusercontent.com/assets/7917826/20958830/84005a16-bc0c-11e6-9b00-a0a049c6b430.png)

Using 1.5.1 Total Economy with spongeforge-1.10.2-2171-5.1.0-BETA-1971

**Comment by DiamondArrow** [comment]
Fixed by updating to 1.5.1

**Comment by DiamondArrow** [comment]
New Issue

**Comment by MarkL4YG** [comment]
Just to make sure: Both the balances __and__ the order are incorrect?

**Comment by DiamondArrow** [comment]
yes

**Comment by Erigitic** [comment]
Would you mind sending your accounts.conf file so I can test this out on my end?

**Comment by DiamondArrow** [comment]
[accounts.zip](https://github.com/Erigitic/TotalEconomy/files/640841/accounts.zip)

**Comment by Erigitic** [comment]
Send it in a pastebin please.

http://pastebin.com/

**Comment by DiamondArrow** [comment]
http://pastebin.com/esPjqXvv

**Comment by Erigitic** [comment]
While looking through the code I realized that I never actually implemented anything to sort the balances. Not sure how I forgot that as that is the whole point of the command. So this issue will be fixed when I actually go about implementing some sorting.

**Comment by Erigitic** [comment]
Fixed by commit 5521953
