### ISSUE TITLE
The plugin isn't showing my balance

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#118]
I gave myself money trough /adminpay, but in-game I can't see the money that I have. That's the output for /balance and /baltop in-game:

![bondia](http://image.prntscr.com/image/716da75b73794bdcb7493463ee8edd0e.png)

In the config, it seems to be working, from accouns.conf:
```
"03c81579-9839-4c0e-bf5e-2d2ece544972" {
    dollar-balance=2060
    job=Unemployed
    jobnotifications=true
}
```

Also, other plugins can't "know" the player balance, such as EasyScoreboard and AdminShop... I'm running 
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b23f81b
    SpongeForge: 1.10.2-2171-5.1.0-BETA-2006
    Minecraft Forge: 12.18.3.2185
    TotalEconomy v1.5.2

**Comment by Erigitic** [comment]
This release was tested on:

Sponge: 5.1.0-BETA-1891
Forge: 12.18.2.2151

There is no guarantee that it will work on later releases. I will go ahead and update Total Economy to the latest versions today and see if I can recreate and fix the issue. Thanks.

**Comment by Erigitic** [comment]
Just updated everything on my end and I am still not able to recreate the issue. Did you happen to change the values of these nodes in the totaleconomy.conf file:

currency-plural=Dollars
currency-singular=Dollar

**Comment by Eufranio** [comment]
Yes, I changed them, and realized that's the issue. When I set it back to Dollars/Dollar, the issue disappear.

**Comment by Erigitic** [comment]
Glad that fixed it.

**Comment by Eufranio** [comment]
When will 1.5.3 be released?

- [ ]

**Comment by Erigitic** [comment]
Most likely tomorrow.
