### ISSUE TITLE
Add localization for translatable messages

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#121]
A messages.conf would be great.

**Comment by MarkL4YG** [comment]
I think this is a good idea for a future release 👍

**Comment by MarkL4YG** [comment]
Did a little research and it seems like Sponge has got something for this in the works:
[SpongePowered/SpongeAPI#1224](https://github.com/SpongePowered/SpongeAPI/pull/1224)

**Comment by MarkL4YG** [comment]
Quick update: Sponge dev. "RysingDragon" has posted something on the sponge forums which might be useful: https://forums.spongepowered.org/t/dragontranslations-translating-plugin-messages/17017

**Comment by Eufranio** [comment]
news?

**Comment by MarkL4YG** [comment]
@Eufranio Neither the Sponge PR nor any other (sponge) official localization support library has shown any activity. It seems like we need to decide on whether to use another plugin for localization support or to directly implement this into TE.  
I honestly don't expect this to come to TotalEconomy anywhere in the near future since there're many features currently being worked on.  
If you want to suggest anything implementation related from libraries to actual code, feel free to do so. I bet @Erigitic will gladly read your proposals :)

**Comment by Eufranio** [comment]
I just wanted a messages.conf by now :/

**Comment by MarkL4YG** [comment]
@Eufranio maybe I'll code something for that within the next few weeks or so. If I do, I'll submit a PR which you'll be able to test and Erigitic can decide to merge.

**Comment by xion87** [comment]
+ 1 for this :(

**Comment by MarkL4YG** [comment]
@xion87 *pssht* if you write ``:+1:`` it's turned into a 👍  ;P

**Comment by Erigitic** [comment]
I think we could at least start on this issue. Make it so some of the messages can be changed, and build on that as time goes on. This way we can get a working version of localization out with 1.6.0.

Here's my idea:

- A messages.conf file will contain all outputted lines throughout Total Economy
- Someway of setting parameters in the messages. I think it would be easiest if we set up pre made arguments. Something like: {level}, {curjob}, {balance}, etc.. So the message (in messages.conf) might look like: "You are now level {level} in the {curjob} job".
- Then we could have a handler class that will handle the messages and convert the parameters into actual values for outputting.

This is just a quick idea that needs to be built on.

**Comment by Eufranio** [comment]
In the future, you could also add placeholders to here (https://ore.spongepowered.org/rojo8399/PlaceholderAPI) instead only in your configs, so they could be used inside the `messages.conf` and outside it.

**Comment by MarkL4YG** [comment]
The placeholder thingy looks kinda promising 🤔

**Comment by Erigitic** [comment]
The only problem I see with this is that, as far as I can tell, it will require every user to download this plugin in order to use Total Economy.

**Comment by MarkL4YG** [comment]
@Erigitic what makes you think that?
"Server Owners
Just drop this plugin into your mods folder and enable any default expansions you want to use in the config file."

**Comment by Erigitic** [comment]
Sorry, by every user I meant every server owner.

**Comment by MarkL4YG** [comment]
Just like a normal dependency 🤔 
You could make it optional (weak dependency) but this would require more code.

**Comment by Erigitic** [comment]
I completely understand that it is just like a normal dependency, I just don't know if it would be best for Total Economy to require another plugin for it to work.

**Comment by Eufranio** [comment]
The idea is not "need" other plugin for it to work. The idea is **provide** your placeholders for PlaceholderAPI when it is installed. You would implement your placeholders that we use in the config file, and IF PlaceholderAPI is installed, provide the placeholders for it.

**Comment by Erigitic** [comment]
But what if it is not installed? Would we have to provide our own implementation? And if we did have to provide our own implementation regardless, what would the use of the PlaceholdeAPI be?

**Comment by Eufranio** [comment]
PlaceholderAPI is **not** installed:
- Create your own implementation of placeholders
- Placeholders would work ONLY in the config file

PlaceholderAPI **is** installed:
- Create your own implementation of placeholders (anyway)
- Hook into PlaceholderAPI and provide your placeholders
- Placeholders would work in the config file and in any other plugin that accepts PlaceholderAPI (just like Holograms will, EasyScoreboard will, BungeeTabListPlus will, chat plugins will, etc).

**Comment by Erigitic** [comment]
That makes a lot more sense. Thanks. I will definitely keep this in mind then, especially since it allows for other plugins to utilize the placeholders.

**Comment by MarkL4YG** [comment]
Just like a weak dependency would do.
Use your own implementation until another is available.
Although implementing the PlaceholderAPI as a weak dependency would require usage of Reflection...

I think using an own implementation from the start or using a way that's proposed in the Sponge PRs is a better way https://github.com/SpongePowered/SpongeAPI/pull/1224.

**Comment by Erigitic** [comment]
I definitely agree with our own implementation from the beginning, especially since I don't expect a full release of localization in version 1.6.0.

**Comment by MarkL4YG** [comment]
Maybe you could tweak the ``AccountManager`` to add a field "lang" and add a ``LanguageCommand`` to set the value of it.
Then just load every configuration from "config/totaleconomy/lang" and when the user should get output, check for whether or not his translation is represented and if not fallback to default.

The language file could be a simple properties style file with just key-value pairs.

**Comment by MarkL4YG** [comment]
Update: The Target Revision of the PR https://github.com/SpongePowered/SpongeAPI/pull/1224 has been changed to 7.0 now. So it might be worth implementing an own system until then.
