### ISSUE TITLE
AdminPay command always returns successful

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#125]
Need to check if the transaction actually went through, if not, don't return as a success.

**Comment by MarkL4YG** [comment]
I would recommend throwing a commandException if the transaction failed.

**Comment by MarkL4YG** [comment]
I also would suggest expanding this to all commands (involving transactions).
``PayCommand`` for example also does return a success when no transaction has been made (e.g. for negative values) [link](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/commands/PayCommand.java#L97)
