### ISSUE TITLE
Balance displaying as 0

### ISSUE THREAD

**Issue by SEC07** [Erigitic/TotalEconomy#131]
Whenever I run the commands /balance, /viewbalance, and /balancetop it displays my current balance as R0 (I have the symbol set to "R") but the config says that it is R100. I've tried /setbalance to set my balance to R100, but it still displays it as R0. I also just noticed that "jobs.conf" has been deleted but that may have happened when I disabled jobs.

**Sponge version**
- spongevanilla-1.10.2-5.1.0-BETA-365

**Plugins installed**
- EasyScoreboards
- holograms-v2.0
- Nucleus-0.16.3-S5-1.10.2-plugin
- PermissionsEx-Sponge
- PlayerShops-1.10.2-1.0.0
- Prism-3.0.0-beta2-21-gdae772d-all
- TotalEconomy-v1.5.3
- worldedit-sponge-mc1.10.2-6.1.5-SNAPSHOT-dist

Don't know how much information you need, but I've including the config files.

**accounts.conf**

"26f69da1-255c-44dd-8ada-1959240a8428" {
    dollar-balance=100
    job=Unemployed
    jobnotifications=true
}

**totaleconomy.conf**

currency-plural=Redollars
currency-singular=Redollar
features {
    jobs {
        enable=false
        notifications=false
        permissions=false
        salary=false
    }
    moneycap {
        amount=10000000
        enable=false
    }
}
startbalance=100
symbol="R"

**Comment by Erigitic** [comment]
The config is showing the balances are still being stored as dollars: "dollar-balance=100". You will need to go into your config and replace all occurrences of dollar with, in your case, redollar.

**Comment by SEC07** [comment]
Thank you! I didn't think that mattered. Works fine now!
