### ISSUE TITLE
Support offline players for /adminpay

### ISSUE THREAD

**Issue by yololetsplay** [Erigitic/TotalEconomy#138]
Hey guys it's me again ;]

Like I said the "fees story" - is it possible that u support offline players for /adminpay soon?
It's like paying fees by all players and the leader/king get's this money even when he's offline.

`/adminpay @a -100` works fine.

Now it's needed that `/adminpay theyololetsplay AMOUNT_OF_ALL_PRESENT_PLAYERS` could be integrated.
Do you have any idea? ;]

Greetz,
Hannes

**Comment by Erigitic** [comment]
@yololetsplay It is definitely possible to support offline players. It is what we are currently doing for the balance top command. I'll look into this and see what can be done.

**Comment by MarkL4YG** [comment]
Well, to support offline players it should in theory suffice to change [this](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/main/TotalEconomy.java#L225) to ``GenericArguments.user``

Doing it for all listed players seems harder though... especially when virtual accounts arrive which I suppose are supposed to be excluded in your fee.

**Comment by yololetsplay** [comment]
Well, that sounds great. Thx alot guys, u doin a good job! ;]
Maybe look at your "EconomyLite" colleagues, they currently support virtual accounts. 
Idk if u can use parts of it's code (I'm not an programmer :P).

If the next guy sub's my #DailyMC project, I will donate you guys.
I really really like ur quick reaction due to issues ;]

**Comment by Erigitic** [comment]
Thanks very much @yololetsplay! Glad to help out!

**Comment by yepidoodles** [comment]
I would much appricate this too :)
