### ISSUE TITLE
Negative Balance

### ISSUE THREAD

**Issue by Pljz** [Erigitic/TotalEconomy#142]
Hello,

Would it be possible to add an option in the config(or just simply disable it entirely) for balances to go below 0? Recently had an issue where when buying a product, the player was able to continue buying it as their balance went into the negatives.

Thanks in advance.

**Comment by MarkL4YG** [comment]
A simple switch shouldn't be that complicated. I'll take a look into that.
@Erigitic 
What do you think about implementing some sort of debt? 
I think this would be a good extension for companies/virtual accounts in the future.

**Comment by MarkL4YG** [comment]
@Pljz so as you might have noticed this issue should be resolved in one of the next updates.

**Comment by Pljz** [comment]
Sounds good.
