### ISSUE TITLE
[Feature request] Option to change order of currency symbol

### ISSUE THREAD

**Issue by Hund** [Erigitic/TotalEconomy#147]
In sweden we have kronor and the symbol is `kr` (100 kr et cetera). Changing the currency to kronor from dollars makes it looks weird as the `kr` gets put first.

It would be nice to have a config options to be able to change the order. :)

**Comment by Erigitic** [comment]
Great idea! I will get this added for 1.6.0. Thanks.

**Comment by Hund** [comment]
Thank you! :)
