### ISSUE TITLE
No funds / payment with TE upgrade

### ISSUE THREAD

**Issue by AsylumDreams** [Erigitic/TotalEconomy#155]
/adminpay user 1000 doesn't prompt any display from TE.
/setbal user 1000 states that the balance has been set to it.

/baltop shows all players are at 0.

  I have a custom currency symbol if that matters - running TotalEconomy 1.5.3 and I believe SpongeForge 1.10.2 2221 5.2.0 Beta 2226.

**Comment by MarkL4YG** [comment]
Please pin your configuration files and make sure that you checked the recipients chat for too.
You may also try out the latest dev release in a testing environment to see if the issue is reproducible.

**Comment by AsylumDreams** [comment]
It is within a testing environment. Functions this way every time. 
 There is some confusion somewhere as I'm getting the message "Your salary of β20 has just been paid." yet there is no money being attributed to any account.

 Just upped to 1.6.0 in TE and still nada.
  As the balance wipe happened after I upgraded to the latest Sponge, I imagined that that's the issue here. But a rollback to SpongeForge-1.10.2-2221-5.1.0-BETA-2142.jar and TE 1.5.3 still fails.

Running just:
TotalEconomy-v1.5.3.jar
Spongeforge-1.10.2-2221-5.1.0-BETA-2142.jar
Pixelmon-1.10.2-5.0.1-universal.jar

===
===

currency-plural=beli
currency-singular=beli
features {
    jobs {
        enable=true
        notifications=true
        permissions=true
        salary=true
    }
    shopkeeper=true
}
startbalance=3000
symbol=β

===
===

Fisherman {
    catch {
        cod {
            expreward="25"
            pay="50"
        }
        pufferfish {
            expreward="250"
            pay="300"
        }
        salmon {
            expreward="100"
            pay="150"
        }
    }
    disablesalary=false
    permission="main.job.fisherman"
    salary=20
}
Lumberjack {
    break {
        leaves {
            expreward="1"
            pay=".01"
        }
        log {
            expreward="10"
            pay="1"
        }
    }
    disablesalary=false
    permission="main.job.lumberjack"
    place {
        sapling {
            expreward="1"
            pay="0.10"
        }
    }
    salary=20
}
Miner {
    break {
        "coal_ore" {
            expreward="5"
            pay="0.25"
        }
        "diamond_ore" {
            expreward="100"
            pay="25.00"
        }
        "emerald_ore" {
            expreward="50"
            pay="12.50"
        }
        "gold_ore" {
            expreward="40"
            pay="5.00"
        }
        "iron_ore" {
            expreward="10"
            pay="0.50"
        }
        "lapis_ore" {
            expreward="20"
            pay="4.00"
        }
        "quartz_ore" {
            expreward="5"
            pay="0.15"
        }
        "redstone_ore" {
            expreward="25"
            pay="2.00"
        }
    }
    disablesalary=false
    permission="main.job.miner"
    salary=20
}
Unemployed {
    disablesalary=false
    salary=20
}
Warrior {
    disablesalary=false
    kill {
        creeper {
            expreward="10"
            pay="1.00"
        }
        skeleton {
            expreward="10"
            pay="1.00"
        }
        spider {
            expreward="10"
            pay="1.00"
        }
        zombie {
            expreward="10"
            pay="1.00"
        }
    }
    permission="main.job.warrior"
    salary=10
}
jobs="Miner, Lumberjack, Warrior, Fisherman"
preventJobFarming=true
salarydelay=300

===
===

"0514cfac-92dd-3f40-b291-602e44579279" {
    dollar-balance=3080
    job=Unemployed
    jobnotifications=true
}
"28bf3b59-74b9-351a-a66a-661ee4ff84b3" {
    dollar-balance=5220
    job=Unemployed
    jobnotifications=true
}
"4becbe9a-914c-38e6-90b1-485b47558329" {
    dollar-balance=10580
    job=Unemployed
    jobnotifications=true
}
"6621cd29-b00b-352e-8303-2368da17d263" {
    dollar-balance=3020
    job=Unemployed
    jobnotifications=true
}
"81491c57-7749-45d3-9636-c997eee78d20" {
    dollar-balance=3360
    job=Unemployed
    jobnotifications="true"
}
"8451b398-5341-3253-9351-20ec4eed9aab" {
    dollar-balance=3020
    job=Unemployed
    jobnotifications=true
}
"9fc406cb-e9b7-44e4-b046-55ad7addfcc0" {
    dollar-balance=4720
    job=Unemployed
    jobnotifications="true"
}
c0d6090f-3931-3aa6-9ce0-73e6e4310c7d {
    dollar-balance=406.57
    job=Unemployed
    jobnotifications=true
}
cbe5a4da-6a75-3f23-8280-03d4de2474eb {
    dollar-balance=3000
    job=Unemployed
    jobnotifications=true
}
fcb45a1e-5971-3981-ba8f-000a5ffd849c {
    dollar-balance=7100
    job=Unemployed
    jobnotifications=true
}

**Comment by MarkL4YG** [comment]
Change your currency settings back to Dollar/Dollars and '$' as Symbol and check if it's working again as it's been the case in #118. If so, I'll check if I can confirm/fix the bug.

**Comment by Erigitic** [comment]
This is an issue with the currency name you are using. If you notice in the accounts.conf you have `dollar-balance` but your currency name is `beli` in the main configuration file. The easiest way to fix this, without deleting configuration files, is to find and replace all occurences of `dollar` with `beli`.

**Comment by MarkL4YG** [comment]
@Erigitic if the beli-balance isn't found, shouldn't TE create the nodes upon balance changes? If so, shouldn't there be ?``dollar-balance`` and ``beli-balance`` nodes?

---
Also by the way: What do you think about grouping this too? I think of a node that would look like this:
```hocon
"<UUID>" {
  balance {
    beli=200
    dollar=4000
    coins=8000
  }
}
```
I could imagine this to be useful to admins with multiple currencies on their server (Servers with multiple nations for example) since this puts all currencies under the same node.

**Comment by AsylumDreams** [comment]
Yep ^_^

 Thanks muchly - alteration of dollar to beli solved it.
 Don't think I'd ever have thought to do that.

Not really the place for this, but Mark's idea for multiple currency nodes is a nice one - opens up the plugin quite a lot. Maybe factor in exchange rates?  Total World Economy ;)

**Comment by MarkL4YG** [comment]
@AsylumDreams Make sure to check if new accounts are created correctly and if all payment types work.

**Comment by Erigitic** [comment]
@MarkL4YG That would be a smart thing to do instead of the current implementation. I'll go ahead and make an issue for this so it can be added in a later release.
