### ISSUE TITLE
[WIKI] Update Job informations

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#157]
The [Job Information](https://github.com/Erigitic/TotalEconomy/wiki/Job-Information) page could use a reminder that those are the defaults and a section for the ``Unemployed`` job.

The [Creating Jobs](https://github.com/Erigitic/TotalEconomy/wiki/Creating-Jobs) page needs a complete overhaul in order to explain ``JobSet``s.

I would consider this medium priority as soon as there's the release of them coming up.  
I will almost certainly take some time in the next few weeks to provide my thoughts on this in a PR but nonetheless here's a reminder ;)

**Comment by Erigitic** [comment]
I've been meaning to do this for quite some time. When I get some free time and 1.6.0 is released I will go ahead and get that all squared away.

**Comment by Erigitic** [comment]
The wiki has been updated
