### ISSUE TITLE
small /pay issue

### ISSUE THREAD

**Issue by OzarkDragon** [Erigitic/TotalEconomy#161]
When we were testing things out on one of out other plugins, I used the /pay command on myself (no one else was online at the time)   

The issue is that it does allow you to /pay yourself  - it says you paid <name>, then you received $ from <name>, but it actually only takes the money from you.

Would a check be able to be added to make it so that you're unable to /pay yourself?

**Comment by Erigitic** [comment]
Interesting. I'll test it out and see if I can recreate it.
