### ISSUE TITLE
Disabled MoneyCap resulting in exceptions.

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#163]
Additionally to the custom money cap TE should also respect the technical limits currently doesn't.
For example, with the cap disabled, paying yourself ``434364732423743e542`` Dollars causes your balance in the config to become (literally) "Infinity" which entirely disables salaries due to a ``NumberFormatException`` in ``#getBalance``.

Imo balances and transactions should ultimately be limited to what TE/Java can handle to prevent unexpected behavior or even bugs as this one.

I would also recommend catching ``NFE``s in such methods. [TEAccount e.g.](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/config/TEAccount.java#L116) This way they can be properly reported.

Instead of ``#hasBalance`` and a default (or fallback) value for ``#getBalance`` I'd suggest using an ``Optional<BigInteger>`` as the return type of ``#getBalance``. This way an invalid balance simply defaults to not having a balance in the specified currency.

**Comment by Erigitic** [comment]
@MarkL4YG Should we just hardcode a max value in then? Because as far as I know, the maximum size of a BigDecimal depends on how much memory there is. So there is no set maximum.

**Comment by MarkL4YG** [comment]
According to the [Java docs](http://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html) a BigDecimal is limited to ``Int32*10^Int32`` which explaines why an Integer of size ``10^542`` exceeds the max. 
I think that looking at the exponent is enough for setting a performant limit to all transactions. Therefore it should be enough to check if the [scale](http://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#scale()) exceeds the scale limit. The actual scale limit could be ``Integer.MAX_VALUE-1`` or just ``Integer.MAX_VALUE/2``.
Using the scale for the limit will enforce an upper and a lower limit simultaneously.

**Comment by MarkL4YG** [comment]
So... I found the limitation. Turns out that ``configurate-hocon`` from Sponge uses ``com.typesafe.ConfigValueFactory`` whichs [``ConfigImpl``](https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigImpl.java#L241) formats BigDecimals into doubles.

**Comment by Erigitic** [comment]
That makes it a lot easier. We'll just cap it to the double max then.
