### ISSUE TITLE
Misleading TransactionResults

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#170]
While investigation possibilities for #169 I stumbled across ``TEAccount#setBalance`` returning a ``deposit`` ``TransactionResult`` and wondered if the amount of the transaction being the target value could be misleading.
IMO a delta would be a better choice for this since the amount of a deposit should only be the final amount if the starting balance was exactly 0.

I also stumbled across the ``/adminpay`` event also returning the new balance as amount of the transaction which obviously is not correct.

**Comment by Erigitic** [comment]
That makes more sense to have it be the difference in balances instead like you stated.
