### ISSUE TITLE
Feature request, jobs for crafting blocks/items

### ISSUE THREAD

**Issue by WildWingX** [Erigitic/TotalEconomy#173]
Is it possible to add crafting as another way to detect in jobs?

As of now the plugin can detect breaking, placing, fishing, and killing for jobs. By adding crafting there can be more job varieties like blacksmith (crafting tools and weapons), carpenter (crafting planks, logs?) and maybe engineer (crafting redstone related items).

**Comment by MarkL4YG** [comment]
I guess that this already is planned along with other types of interaction. It's part of the job update that's in the making.

**Comment by Erigitic** [comment]
Currently in the process of working on a "create" action that will allow for a lot more options in terms of job creation. Thanks for the suggestion.

**Comment by Erigitic** [comment]
This issue is necessary for #49 and #25

**Comment by Erigitic** [comment]
Closed in favor of #49 and #25
