### ISSUE TITLE
1.6.0 Alpha 3

### ISSUE THREAD

**Issue by EmanYm** [Erigitic/TotalEconomy#174]
I installed the dev version and started up my test server
https://hastebin.com/olakosidef.md
Of course this broke everything that rely on an economy plugin being present.

SpongeForge 5.2.0β2320
TotalEconomy v1.6.0α3

I will go back a version to 1.5.3 for now.

**Comment by Erigitic** [comment]
This seems to be caused by the main configuration file not being loaded. Also, this version was tested on spongeforge-1.10.2-2171-5.1.0-BETA-2010. You seem to be using a newer version which could explain the issue.

**Comment by EmanYm** [comment]
It didn't work at first, but deleting the config folder helped.  It seems the config got corrupt somewhere along the line.
Perhaps I will get it all set up and try the 1.6 version again.

**Comment by MarkL4YG** [comment]
@Erigitic You may want to change [this line](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/main/TotalEconomy.java#L233) to include the IOE in the output. (Just add ``e`` as the second argument)

**Comment by Erigitic** [comment]
@MarkL4YG Good idea.
