### ISSUE TITLE
Server Freeze Error with /pay 

### ISSUE THREAD

**Issue by PureRiddle** [Erigitic/TotalEconomy#179]
We had a player come on our server and use the following command and spammed it continuously until the server froze up "/pay Obstigated 111111111111111111111111E1111111111111111111111111111"

**Comment by Erigitic** [comment]
What version of Total Economy are you using?

**Comment by PureRiddle** [comment]
I am running Total Economy V 1.5.3. And Spongeforge 1.10.2 2281 5.2.0 BETA 2366.

**Comment by MarkL4YG** [comment]
@PureRiddle then please try the 1.6.0-dev release on a testing environment. You should see the issue disappearing.

**Comment by PureRiddle** [comment]
Thank you, do you know when it might be out of development? I will gladly test the version on my test server but would fear putting it on a live variant before its released fully.

**Comment by MarkL4YG** [comment]
@PureRiddle We are aware of that an of course even advise not to use dev builds in live variants.
Sadly the only reliable way to determine the status of the update is to generally monitor the repository and the [milestone](https://github.com/Erigitic/TotalEconomy/milestone/11). Especially the milestone can indicate whether the release is finished codewise or not.

**Comment by Erigitic** [comment]
As @MarkL4YG said, monitoring the milestone is a great way to get a general idea of when a development version is going to become a release version. Currently, we are very close to finishing 1.6.0
