### ISSUE TITLE
Setting up the MySQL

### ISSUE THREAD

**Issue by Jamm22** [Erigitic/TotalEconomy#181]
Hey I was trying to set up the MySQL in the config,

This is my current MySQL config:

database {
    enable=true
    password="censored"
    url="jdbc:mysql://localhost:3306/"
    user="totaleconomy"
}

I get the following errors when I join:

https://pastebin.com/DctQ8KP7
And:
https://pastebin.com/Lz1aV8G7

And whenever I use a TotalEconomy command I get this error:

https://pastebin.com/xGEtuTyc

I am running FTB Beyond 1.9.0:

spongeforge-1.10.2-2281-5.2.0-BETA-2401
forge-1.10.2-12.18.3.2281-universal
FTBserver-1.10.2-12.18.3.2316
minecraft_server.1.10.2
SpongeBootstrap-0.3.0

Add me on discord if you feel like:
Jamm#4460

- Jamm, Community owner Sector 24 Seven.

**Comment by MarkL4YG** [comment]
There seems to have been an issue during initialization. Please look through your log and see if you're able to spot that error (should also be an Exception written to the log).

And just in general: You do have created a database "totaleconomy" to which the user "totaleconomy" has ``ALL`` access?

**Comment by MarkL4YG** [comment]
By the way @Erigitic I think a way to edit the database name would be a nice idea.  
Maybe also add a ``template.sql`` file to set up the database.

**Comment by Jamm22** [comment]
Problem solved.

No clue how.
But I did a fresh install of LAMP and PHPMyAdmin.

- Jamm
