### ISSUE TITLE
[Wiki] Update some documentation

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#182]
I think of adding a page on the details of TEs SQL support. I currently can't submit pages though since contributions to the wiki seem to be disabled.

**Comment by Erigitic** [comment]
From what I can see, allowing contributions to the wiki will allow anyone to change the contents of a page without needing permission. That could be bad. If you could, write up the page and post it on this issue. Then I'll transfer it over to the wiki. Thanks.

**Comment by Erigitic** [comment]
The wiki has been updated to include information on database support.
