### ISSUE TITLE
Create messages.conf file to allow for custom messages

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#185]
Currently all messages are set by us and there is no way for users to customize these messages. A file containing these messages to allow for users to customize them is needed.

**Comment by Erigitic** [comment]
This would help to make progress on #121

**Comment by MarkL4YG** [comment]
Do you think we should be using a special translator class or directly get the messages from the config.

**Comment by Erigitic** [comment]
My thought was that we'd grab the custom messages from the messages.conf file as is, and from there translate them within the plugin. Though this would assume all the messages in there are in English. 

This brings up the question of weather or not we should do automatic translation, or if we should leave it up the users?

**Comment by MarkL4YG** [comment]
I think automatic translation is way to complex for our purpose. I think a good idea is a ``messages-<lang>.conf`` (maybe in HOCON structure) with key-value associations where users can specify their messages themselves.
Having a <lang> parameter would allow us to ship basic or submitted translations in the plugin resources. And users could select the lang using a key in the main config.

I could provide a ``messages-de.conf`` for example.

**Comment by Erigitic** [comment]
I think that's the way to go then because like you said, automatic translation is a bit to complex.

**Comment by MarkL4YG** [comment]
Remember that we need aliases like ``%recipient%`` and ``%job%`` to insert the dynamic data.
