### ISSUE TITLE
farmer job

### ISSUE THREAD

**Issue by Mikendike** [Erigitic/TotalEconomy#190]
none of the exp or money is given when the job farmer breaks the crops but it works when they place crops, why is that?

**Comment by MarkL4YG** [comment]
That sounds like messed up job sets... Can you please paste your jobs configs to hastebin.com and link them here?

**Comment by Erigitic** [comment]
@Mikendike Were you able to get this fixed?

**Comment by Erigitic** [comment]
Closing this as it has been quite a few months without a reply. @Mikendike Please feel free to reopen if you are still encountering issues with this. Thanks.
