### ISSUE TITLE
[Jobs] Meta-ID support (sort of)

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#197]
Currently blocks are only identified by their name. But some(tm) modifications additionally use meta-ids or ``BlockProperty``s to identify different blocks with the same dictionary name. This makes TE see (e.g.) tin and copper like they're the same ore since both can have the ID/Name ``<modid>:ore``.
Additionally some debug tool for admins to get such information would be nice.

I've already started working on a solution for this and will submit a PR shortly.

This will resolve / See discussion: #193

**Comment by MarkL4YG** [comment]
@TheAJArts here's your notification for the new issue.

**Comment by TheAJArts** [comment]
Thank you! Yes, if there is a way of obtaining this information with less effort, it would lower my stress levels.. I could also possibly use said information in other plugins, as well.

**Comment by MarkL4YG** [comment]
Please take a look at the pull request. If you'd test the preview it'd be very helpful for us.

**Comment by MarkL4YG** [comment]
As you can see I resubmitted the pull request. This time only the two relevant commits are included 👍
