### ISSUE TITLE
Job that pays for killing mobs

### ISSUE THREAD

**Issue by JoeSchmo2840** [Erigitic/TotalEconomy#2]
I would love to see if youd be willing to allow players for getting paid to kill monsters or other players with a configurable amount. Possibly even configurable to the point of how much diff mobs earn you i.e. zombies drop 50 bucks, but wither bosses drop 1,000 bucks. Thanks in advance!

**Comment by Erigitic** [comment]
I will definitely be doing this. I will add to this into the next update along with at least one other job. This update should come out sometime this week. Thanks for the suggestion.

**Comment by JoeSchmo2840** [comment]
Thanks a ton!

**Comment by Erigitic** [comment]
I have been looking into this and I do not believe that an event that handles entity deaths or player kills is implemented yet. I will keep looking but if I cannot find anything then the money for kills will have to wait for these events to be implemented. Sorry about that but it will defiantly be added as soon as possible.

**Comment by KAISERslin** [comment]
It is implemented in Looty using the Total Economy API.
https://forums.spongepowered.org/t/rpg-looty-custom-items-item-drop-system-grinder/9278

**Comment by Erigitic** [comment]
Just a heads up, I do have plans to add a job that will pay users for killing mobs. This should not be an issue though since users that use both Looty and Total Economy can remove this job or disable jobs completely through Total Economy.

**Comment by Erigitic** [comment]
Set for release in version 1.2.0

**Comment by KAISERslin** [comment]
It's optional on my end as well. There shouldn't be any conflict. Cheers
