### ISSUE TITLE
Job Requirements doesn't work

### ISSUE THREAD

**Issue by bombaroberta** [Erigitic/TotalEconomy#200]
Hi all.
When i add a new job i use this and i edit with the level , name, sets and the job requirements but when i use in game i can't switch on the second job and i saw this:"minerrank2 does not exist"
This is the jobs.conf and i have added the same sets as miner but with a new amount of a block:
```
miner {
    require {
        job=""
        level=0
        permission="totaleconomy.job.miner"
    }
    salary=20
    sets=[
        ores
    ]
}
minerrank2 {
    require {
        job="miner"
        level=25
        permission="totaleconomy.job.minerrank2"
    }
    salary=30
    sets=[
        ores2
    ]
}
```
If someone knows something about this can he help me, please.
Have a good day all.

**Comment by MarkL4YG** [comment]
Hey there,
If that's your entire jobs configuration be aware that its format should look like this:
```hocon
jobs {
  miner {
    require {
      job=""
      level=0
      permission="totaleconomy.job.miner"
    }
    salary=20
    sets=[
      ores
    ]
  }
  minerrank2 {
    require {
      job="miner"
      level=25
      permission="totaleconomy.job.minerrank2"
    }
    salary=30
    sets=[
      ores2
    ]
  }
}
salarydelay=300
```
Note that the ``jobs`` root node would be missing.  

If that's not your entire jobs config please consider using [GitHub-Gists](https://gist.github.com) to send your ``totaleconomy.conf``, ``jobs.conf``, ``jobsets.conf`` and the corresponding server log so we can properly see if there's something else wrong that may cause this.

**Comment by bombaroberta** [comment]
Ok thank you for your answer and here are configurations :
https://gist.github.com/bombaroberta/3adf04c97fffa706e66c887fd5f3f851
https://gist.github.com/bombaroberta/99134cd4cbb7349adbc1db9fab1d985a
https://gist.github.com/bombaroberta/cdace2b54673a38aea484168e425b23d

I did not find any log similar to jobs
just this in game:
https://image.noelshack.com/fichiers/2017/35/1/1503943047-capture.jpg
and this in the console:
https://image.noelshack.com/fichiers/2017/35/1/1503943052-capture2.jpg
I hope you will find with this.

**Comment by MarkL4YG** [comment]
Okay, if quickly looked over the config files and there seems to be no error in them.  
So I'd like to see the server log as the exception seems to be related. You can find the log in your ``logs`` directory by the way.  

Also: You can add multiple files to one gist - just so you know ^^

**Comment by bombaroberta** [comment]
Ok this is all I have in my log file:
(I moved all log in other file and launcher my server i tried to use /job and i left my server before turning it off and send you these logs)
https://gist.github.com/bombaroberta/10d2068def31577fb91d0827295fb9b4
good luck for finding something in this, if you would just 1 file in particular you can say it.
Again thx to try to help me, usually, i find by myself but now i really don't know where is the problem.

**Comment by MarkL4YG** [comment]
First thing I noticed: ``java.lang.NumberFormatException: For input string: "2.26"`` - you have some exp nodes with decimals but TotalEconomy only supports Integers for those. ``"2"`` for example. (Important note: There is a PR pending that changes the format from ``"<number>"`` to ``<number>`` values. So that may sightly change in the future.)

Also: What version of TotalEconomy are you using? There's a mismatch between the source pointers in the log and the current repository so I currently can't closer pinpoint the exceptions.

**Comment by bombaroberta** [comment]
I use totaleconomy 1.7.0 and this means that I can not use decimals? Because i need to have a precise value for a better gameplay.

**Comment by Erigitic** [comment]
You cannot use decimal numbers for exp rewards. It must be a whole number (1, 2, 3, etc.).

**Comment by MarkL4YG** [comment]
@bombaroberta if you want ``2.2`` for example you could multiply everything by 10 and you would have the same precision 😉

**Comment by bombaroberta** [comment]
I changed all amount but now when i select a job with requirements i have this : 
job miner2 does not exist!
https://gist.github.com/bombaroberta/00d57de261fb32ddc4d18911de8c9dae

**Comment by MarkL4YG** [comment]
Server logs required ^^  
The ``fml-server-latest.log`` should be enough though.

**Comment by bombaroberta** [comment]
yes sorry 
https://gist.github.com/bombaroberta/03545d2afd9571caa23e66bac7f16d07

**Comment by MarkL4YG** [comment]
So .... I say no obvious error. Assuming that this is the correct log where you actually had the missing job error: Are you sure that no other plugin overwrites TotalEconomy? I saw buycraft for example and I think it may have jobs support too... Anyways... try: ``totaleconomy:job set <job>``

**Comment by bombaroberta** [comment]
The same issue "job mineurRang2 does not exist!"
https://gist.github.com/bombaroberta/9470ef5e8c63c94134351856de11cb98
It's strange because all job with requirements doesn't work unlike other without requirements.

**Comment by MarkL4YG** [comment]
Could you please list all your installed plugins. I will also prepare a debug release for you so we can get additional information.

**Comment by bombaroberta** [comment]
-Adminshop 
-BuycraftX 
-CmdCalendar (1.1.2)
-CommandSigns (1.3.1)
-EasyScoreboards 
-FlexibleLogin 
-Latch (0.4.3)
-LuckPerms (3.3.18)
-Nation (2.6)
-Nucleus (1.1.0)
-nuvotifier (2.3.5)
-SimpleVitifierListener (0.6.5)
-SkinsRestorer (13.1.3)
-SpongyChest (0.4.8)
-TotalEconomy (1.7.0)

**Comment by MarkL4YG** [comment]
So... I used your ``jobs.conf`` and ``jobsets.conf`` in my development environment and had no trouble using ``job set miner2``. That's about where I discovered that the ``TEJob`` class apparently does not have any mechanism that loads that requirement node at all. I guess that got lost somewhere so I'll add a PR to put that back into the develop branch.

**Comment by MarkL4YG** [comment]
@bombaroberta Please verify (with the next release or after own compilation) if the issues has been fixed and re-open if not.
