### ISSUE TITLE
Changes to messages_en.conf not being reflected in game.

### ISSUE THREAD

**Issue by JoshHartley** [Erigitic/TotalEconomy#202]
So I just installed the plugin a couple hours ago, (minecraft 1.10.2), and it works great. However I've been trying to modify the language file, and the changes I've made are not appearing in game at all. I checked that the language in the main config file was set to en, have tried editing while the server was stopped, tried using sponge reload while it was running, and nothing is working. I wouldn't be surprised if it was something dumb I'm missing, but help would be greatly appreciated.

**Comment by MarkL4YG** [comment]
hmm... that seems weird - Can you provide some more information about your setup? TE, Sponge(+API), Minecraft versions and the server logs (either via github gists or haste-/pastebin)?

**Comment by Erigitic** [comment]
There was an issue that occurred during development that caused the messages file to be remade every time the server started, but this should have been fixed. Are your changes in the `messages_en.conf` file being overwritten at all? Or do they still persist after a server restart?

**Comment by JoshHartley** [comment]
@Erigitic No, the changes I made to the file still persist after a server restart

@MarkL4YG It's installed on an FTB Beyond server, which is Minecraft 1.10.2
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2610
Minecraft Forge: 12.18.3.2281

https://gyazo.com/f8e38010730e3859b9c0f1e2301c2ab6
https://pastebin.com/QSF092JG

* also note, I had the actual release, rather than the dev release installed when posting the issue, I just though I'd give the dev release a try this morning, but it still has the same issue.

**Comment by MarkL4YG** [comment]
From what I've seen there're no obvious errors in the log. And aside from the Sponge plugins using their own folder there doesn't seem to be anything abnormal too.  
Have you checked that you use the ___stable___ 1.7.0 version of TotalEconomy?

**Comment by JoshHartley** [comment]
Yes, I've definitely used the stable 1.7.0 version of the plugin, as well as the dev release afterwards, to see if it possibly worked correctly in that release.

**Comment by MarkL4YG** [comment]
hmm... that seems rather weird... Can you reproduce this using a local instance on your desktop or is it only happening on the server?  

@Erigitic Just noticed that TE only drops a warning [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/util/MessageManager.java#L79) and the exception is not attached.

**Comment by Erigitic** [comment]
Try disabling any one of the features in the `totaleconomy.conf` file. See if that actually disables the feature in the server. This is just to test to make sure configuration files are even being read in the first place.

On another note, do you have the `config-dir` setting properly set to the location of the config files in the `global.conf` file? Because your file structure is not default, so that needs to be properly set so Sponge knows where to look.

**Comment by JoshHartley** [comment]
`    general {
        # The directory for Sponge plugin configurations, relative to the 
        # execution root or specified as an absolute path.
        # Note that the default: "${CANONICAL_GAME_DIR}/config"
        # is going to use the "plugins" directory in the root game directory.
        # If you wish for plugin configs to reside within a child of the configuration
        # directory, change the value to, for example, "${CANONICAL_CONFIG_DIR}/sponge/plugins".
        # Note: It is not recommended to set this to "${CANONICAL_CONFIG_DIR}/sponge", as there is
        # a possibility that plugin configurations can conflict the Sponge core configurations.
        config-dir="${CANONICAL_GAME_DIR}/spongeplugins/config"
        # Disable warning messages to server admins
        disable-warnings=false
        # Enabled sleeping between chunk saves, beware of memory issues
        file-io-thread-sleep=false
        # Additional directory to search for plugins, relative to the 
        # execution root or specified as an absolute path.
        # Note that the default: "${CANONICAL_MODS_DIR}/plugins"
        # is going to search for a plugins folder in the mods directory.
        # If you wish for the plugins folder to reside in the root game
        # directory, change the value to "${CANONICAL_GAME_DIR}/plugins".
        plugins-dir="${CANONICAL_GAME_DIR}/spongeplugins"
    }`

Config: https://pastebin.com/qiuxUnnk
Language: https://pastebin.com/2xyP9vQR
* note, I've tried using (and altering) the language file included within the git repository, and have also reinstalled the plugin multiple times to get a completely fresh copy of the file.

And yes, the config itself is working. Disabling/Enabling the jobs feature is working fine. I also have SQL setup in the config, which is working fine as well.

**Comment by Erigitic** [comment]
Alright, I think I've realized what happened. I made changes after 1.7.0 was released that fixed the message issue...but I never released those changes. So I'm going to do that now. I'm really sorry about that.

**Comment by Erigitic** [comment]
Here you are: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.7.1. Sorry for the trouble. Let me know if this works for you. Thanks a bunch!

**Comment by JoshHartley** [comment]
Aye, it indeed works now, thank you so much :)

---

However, not to make more work for you, but just so you know...
With this version, /sponge plugins reload now gets a null pointer from the plugin. 
https://pastebin.com/TszwHMnY

Like I said, don't wanna make more work for you by pointing this out, I'm perfectly content with simply restarting the server to update changes, but it's an issue I ran into, so ya.

**Comment by MarkL4YG** [comment]
@JoshHartley That'll be fixed at some point but nontheless: You shouldn't reload live server anyways ^^

**Comment by MarkL4YG** [comment]
hmm... This is Off-Topic but I wonder how 
```hocon
plugins-dir="${CANONICAL_GAME_DIR}/spongeplugins"
```  
is actually working for you 🤔 ... I tried setting that to  
```hocon
plugins-dir="${CANONICAL_GAME_DIR}/mods_sponge"
```  
and SongeVanilla still loads from ``mods/`` ... 🙄

**Comment by JoshHartley** [comment]
Idk, it just worked :P My sponge jar is still in the mods folder though, and using `/sponge plugins` lists all of the forge mods in the `mods` folder, as well as the sponge plugins in the `spongeplugins` folder.

**Comment by MarkL4YG** [comment]
I've already figured that out. It was a bug whichs fix was never pushed to stable (API-5).
