### ISSUE TITLE
Change Job from signs

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#21]
Not sure if this is something that should be added. Needs input.

**Comment by AlvarOsO** [comment]
This is a feature that i look forward to. With this, a server owner can make that you only can change jobs with signs, to make a real RPG experience. I would suggest to add too Villager and Object job change. Villager be like when you right click two times on a especial villager (First for info on the job, second to confirm the change) it changes your job. And Object when you have a unique item in your inventory, like a book with a special NBT, you get that job.
I know this suggestions could make a feature request on their own, but is tied to the implementation of this issue, so I think this is a good place to say it.
Note: No native english speaker.

**Comment by Erigitic** [comment]
I am glad you replied to this because I was about to scrap the idea. I will definitely be adding this into the next version of Total Economy. I also like the idea of working with Villagers and I do have some stuff planned that will utilize villagers. Thanks again.

**Comment by Erigitic** [comment]
Complete
