### ISSUE TITLE
Multi-Currency support

### ISSUE THREAD

**Issue by Krosta8** [Erigitic/TotalEconomy#213]
Hello,
I read on your wiki page (Sponge), that this plugin supports multi-currencies, but here the wiki says, that Total Economy currently supports only one currency. 

What's the truth? 😄 I would like to use your plugin, but I need to have two currencies.

And with this I have another question. 
Am I able to set for which currency should be an item sold in Nucleus?

**Comment by MarkL4YG** [comment]
As you can see e.g. [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/commands/PayCommand.java#L71) and [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/config/TEAccount.java#L264)  TE does have multi-currency support and Nucleus has to decide which currency to send with the withdrawal/deposit. It's the TE documentation being outdated what caused the confusion.

**Comment by Krosta8** [comment]
Okay, thank you.
Unfortunately, when I used it on API 7.0.0 (I know, it is not supported right now), I just got error everytime.

**Comment by MarkL4YG** [comment]
Yeah that's due to the breaking cause-tracking changes introduced with MC 1.12. A bleeding release is slowly making its way though.

**Comment by Erigitic** [comment]
I just updated the wiki so it should now contain proper information regarding multiple currencies.
