### ISSUE TITLE
Error occurred while executing /bal command.

### ISSUE THREAD

**Issue by rockclimber36** [Erigitic/TotalEconomy#217]
![image](https://user-images.githubusercontent.com/24191711/32150415-0ca85e96-bcd8-11e7-9e0b-43dd3702be39.png)
When ever I running a /bal command I get this error. I am running sponge api 6.1 minecraft 1.11.2

**Comment by rockclimber36** [comment]
Scratch that its any time I run any command.

**Comment by Erigitic** [comment]
Does it occur with other plugins or just Total Economy?

**Comment by rockclimber36** [comment]
Just total Economy.

**Comment by rockclimber36** [comment]
it was working before and just started doing this.

**Comment by Erigitic** [comment]
What version of Total Economy?

**Comment by Erigitic** [comment]
Also please send the console log

**Comment by rockclimber36** [comment]
TotalEconomy-1.7.1 
[latest.log](https://github.com/Erigitic/TotalEconomy/files/1425654/latest.log)

**Comment by Erigitic** [comment]
Send the log in a gist please: https://gist.github.com/

**Comment by rockclimber36** [comment]
https://gist.github.com/rockclimber36/c4ea471b34899dcda657d6bc7058ae36 
Line 171

**Comment by rockclimber36** [comment]
https://gist.github.com/rockclimber36/c4ea471b34899dcda657d6bc7058ae36
Line 171

**Comment by Erigitic** [comment]
I'm not seeing anything related to Total Economy in the console. Do you have another plugin that may be conflicting with Total Economy?

**Comment by rockclimber36** [comment]
Nope.

**Comment by rockclimber36** [comment]
This is what comes up in counsel when I type /bal. Netty Epoll Server IO #7/ERROR io.netty.handler.codec.EncoderException: String too big (was 32779 bytes encoded, max 32767)

**Comment by Erigitic** [comment]
That seems to be an error with Netty, not Total Economy. I'd check with them.

**Comment by Erigitic** [comment]
Actually, what plugins do you have installed?

**Comment by MarkL4YG** [comment]
Please re-install Sponge in a second environment and see if the error also occurs there.

**Comment by rockclimber36** [comment]
ActiveTime-s6.0-v1.2.4.jar
AdminShop-1.10.2-1.8.2-universal.jar
BetterCommandSigns-0.0.4.jar
BetterKits-0.9.6.jar
CatClearLag-0.8.jar
ChatUI-1.0.0.jar
CmdCalendar-mc1.10.2-v1.1.2.jar
CmdControl-s6.0-v1.0.1.jar
CommandBooks-v1.4.0.jar
walletdrop-5.2.0-0.2.3.jar
XtraPunish-2.0.jar
TotalEconomy-1.7.1.jar
Nucleus-1.1.3-LTS-S6.0-MC1.11.2-plugin.jar
nuvotifier-universal-2.3.4.jar
PlaceholderAPI-4.1.jar
projectcore-5.2.0-0.1.5.jar
pwnfilter-3.4.0.jar
RankUpper-2.2.2-b133_Sponge.jar
spongeforge-1.11.2-2476-6.1.0-BETA-2712.jar

**Comment by rockclimber36** [comment]
Thats a list of plugins I have.

**Comment by rockclimber36** [comment]
Im getting a error from the server

31.10 14:44:15 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'bal' for source GCEntityPlayerMP['rockclimber36'/10891, l='Hub', x=18.75, y=82.50, z=56.29]: org/apache/commons/lang3/text/StrLookup
31.10 14:44:15 [Server] INFO java.lang.LinkageError: org/apache/commons/lang3/text/StrLookup
31.10 14:44:15 [Server] INFO at org.apache.commons.lang3.text.StrSubstitutor.<init>(StrSubstitutor.java:264) ~[minecraft_server.1.11.2.jar:?]
31.10 14:44:15 [Server] INFO at com.erigitic.util.MessageManager.getMessage(MessageManager.java:103) ~[MessageManager.class:?]
31.10 14:44:15 [Server] INFO at com.erigitic.commands.BalanceCommand.execute(BalanceCommand.java:85) ~[BalanceCommand.class:?]

**Comment by Erigitic** [comment]
Do you happen to have a `messages_en.conf` file in the totaleconomy folder?

**Comment by Erigitic** [comment]
Also, I just tested this on the latest version of Sponge Forge for 1.11.2 and I am not able to recreate the issue. Were you able to get around to doing what @MarkL4YG said?

**Comment by Erigitic** [comment]
And what's in your main configuration file?

**Comment by MarkL4YG** [comment]
The exception from the image suggests class file duplication. Either the Sponge installation got currupted with two distributions of that apache library, a plugin falsely ships its own copy or two plugins happen to ship that lib.

That's why I asked for clean-install results as we may be able to rule out some of the possibilities here.

**Comment by Erigitic** [comment]
@rockclimber36 Were you able to get this fixed?

**Comment by Erigitic** [comment]
Closing this issue as it's been over a month since a response. If this is still an issue @rockclimber36, I'll reopen it.
