### ISSUE TITLE
plugin conflict

### ISSUE THREAD

**Issue by pyscho974** [Erigitic/TotalEconomy#218]
using the 1.7.0 legacy build for 1.10.2 i get a conflict with wallet drop.  somehow its stopping wallet drop from issuing currency for mob kills even with features turned off in config.  im assuming that its not actually turning off the feature of job warriors properly for wallet drop to work correctly. originally thought they would work side by side since wallet drop is able to drop the currency as items on ground at mob kill. also im on java 1.8_144 with spongeforge-1.10.2-2477-5.2.0-BETA-2698 and walletdrop-5.2.0-0.2.3. 

any suggestions would be helpful.

also note that for a moment i had wallet drop  currency items dropping . after restarting the server it stopped doing this.

**Comment by Erigitic** [comment]
Send your `totaleconomy.conf` and `jobs.conf` files in gists please.

**Comment by pyscho974** [comment]
https://gist.github.com/pyscho974/ed25b5029cae8601a4d0e09a50e33ca7  is no jobs config due to the settings still seems is something blocking wallet drop from issuing currency.  
tested wallet drop and it does work just not with total economy for some strange reason.

**Comment by Erigitic** [comment]
Any console errors?

**Comment by MarkL4YG** [comment]
I would be very confused by TE influencing mob kill rewards properly triggered...

As Erigitic mentions the server logs would be very helpful.
Please attach them to the gist.

**Comment by pyscho974** [comment]
hmm just started up my test bed again..  strange that it wont show up in chat now. have mine to put the message into chat.  
not boasting another plugin but with economy lite had no issues to wallet drop..  but wasnt the desired plug in. 
 yes mark im generating new log files on my test bed to see if i can find something ive over looked. 
 no one had even noticed a money pay on the live server.

**Comment by pyscho974** [comment]
https://gist.github.com/pyscho974/87ca03bc2c762ba6cc4061f386f290f5 this is the log file.. im having issues reading threw it.. but at 15:11:04 time stamp i set balance to zero and killed several mobs. i gained currency but not exactly sure why its not outputting the action in game as currency earned. starting to think its maybe spongeforge or wallet. i do appreciate the time to look at this tho and assist me on it.  originally used older version of spongeforge when i first tested most the compatibility . even rolling back to economy lite was not working like used to which is why thinking when i updated sponge it broke things that i wasnt noticing lol

**Comment by Erigitic** [comment]
Glad to help. I'd let the developer of Wallet Drop know just in case it is something on their end.

**Comment by MarkL4YG** [comment]
So to be clear: You get your money when you kill mobs but wallet drop doesn't notify you?

Habe you tried using TEs "kill" jobSet node instead?

**Comment by pyscho974** [comment]
well i would have but was just way to many mobs to list and seems i wasnt able to set mobs other then vanilla to work in it. maybe user error on my part. but wallet drop somehow listed every mob in the pack automatically. and it did this based on each dimension so a config for each separately

**Comment by MarkL4YG** [comment]
Afaik non-vanilla mobs should work too. If you list their names/ids correctly.

The trait support currently PR'd should help you as it includes a debugging feature that tells you the string to use.

**Comment by pyscho974** [comment]
whats pr'd?  im really slow at learning new things with all this lol. i spend a few days just trying to understand what i currently got. and always learning more it seems to what already using. but space astronomy 2 pack has so many mobs its way to much to have to type out lol

**Comment by MarkL4YG** [comment]
Pull-Request-ed

**Comment by MarkL4YG** [comment]
There's a pull request by me currently waiting for approval which includes additional debugging tools?
