### ISSUE TITLE
Not working fully.

### ISSUE THREAD

**Issue by TheIdioticOtaku** [Erigitic/TotalEconomy#220]
I don't mean to be a bother, but I just today learned about sponge and installed it and this plugin. It doesn't seem to be working fully. I can do /balance but that's about it. I only have the base download from sponge, is there something else I need to do? It's saying currency doesn't exist? I'm confused. I would appreciate any help in learning more about sponge, the plugins, and how to fix whatever issue it is I'm having with the plugin.

**Comment by Erigitic** [comment]
Any console errors? Send your configuration files in gists (https://gist.github.com/) and post them here. And take screenshots if you can.

**Comment by TheIdioticOtaku** [comment]
Here is the list of configuration files under TotalEconomy- https://gist.github.com/TheIdioticOtaku/e543e89e8789a48cf81248b346c0d7b8
And here is the error screenshot. I also included a screenshot of my mods/plugins. The plugins are highlighted, and the version of totaleconomy I have is the most recent I believe. If possible, I would also love more info on how to work the other features of this plugin, I cant seem to find anywhere to explain. If there is somewhere to explain more in depth how the plugin works, that would be great! It is my first time ever using an economy plugin. Im not very experienced on plugins or running a server either, so I apologize if the information I'm giving isn't what was asked for, it was what I got from it. 
![mcerror1](https://user-images.githubusercontent.com/33495197/32603667-3000e3a0-c510-11e7-8a87-6a61492a06b8.png)
![mcplugins](https://user-images.githubusercontent.com/33495197/32603668-300fac32-c510-11e7-82aa-b0670ce7148a.png)

**Comment by MarkL4YG** [comment]
You're using Sponge API version 7 please be adviced that you'll need to download the experimental API-7 release of TotalEconomy in order for the plugin to work at all.

**Comment by Erigitic** [comment]
Here's the API 7 build: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.7.1-API_7. Let us know how that works for you. 

The wiki contains information that may help you out in understanding the different features Total Economy has to offer: https://github.com/Erigitic/TotalEconomy/wiki. The wiki is a bit out of date, but should still prove helpful.

**Comment by TheIdioticOtaku** [comment]
Oh, thanks! I can't wait to get my friends on and test all the features out. c:

Update: It works! I'm so excited to get my server town going!
