### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by ALPHAWOLF2156** [Erigitic/TotalEconomy#223]
Sponge Version:  1.10.2
Forge Version:  1.10.2
Total Economy Version:  1.7.1

Ok so I have tried using the commands. I've allowed the permission, but every time I use the commands this shows up. Error occurred while executing command: null . Can you tell me how to fix this?

**Comment by Erigitic** [comment]
Any errors in the console? If so, send the log file in a gist.

**Comment by ALPHAWOLF2156** [comment]
java.lang.nullpointerexception

**Comment by Erigitic** [comment]
I'm gonna need to see the entire log file. https://gist.github.com/

**Comment by ALPHAWOLF2156** [comment]
https://gist.github.com/ALPHAWOLF2156/6290ae1eecfcbe468986344b52d64537

**Comment by Erigitic** [comment]
Could be an issue with incompatibility with 1.10.2. I'll test this out on my end sometime today and see if I can recreate it.

**Comment by ALPHAWOLF2156** [comment]
Is there any other version I could use for 1.10.2?

**Comment by Erigitic** [comment]
1.7.0 for 1.10.2 can be downloaded here: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.7.0-LEGACY.

**Comment by ALPHAWOLF2156** [comment]
Thank You

**Comment by ALPHAWOLF2156** [comment]
It's working. Thank you

**Comment by MarkL4YG** [comment]
Close?
