### ISSUE TITLE
Problem with commands

### ISSUE THREAD

**Issue by shiosakun** [Erigitic/TotalEconomy#224]
Sponge Version:  7.0.0.0
Forge Version:  14.22.1.2485
Total Economy Version:  1.7.1

### Description of issue
when I try to use any command, this is displayed in the char (org/spongepowered/api/event/cause/NamedCause).

### Console errors

org/spongepowered/api/event/cause/NamedCause

**Comment by MarkL4YG** [comment]
This may be the cause system having changed slightly again.
Can you please provide your server logs using Github-Gists?

**Comment by Erigitic** [comment]
Look like you are using Total Economy 1.7.1, which was made to work with API 5 and API 6. Use this for API 7 and SpongeForge 1.12.2: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.7.1-API_7

**Comment by MarkL4YG** [comment]
Ah good catch @Erigitic 👍

**Comment by shiosakun** [comment]
OH, sorry about that
Ty for answering soon
