### ISSUE TITLE
1.12.2 Command Issues

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#227]
Minecraft: 1.12.2
SpongeAPI Version:  7.0.0-SNAPSHOT-0ede943
Sponge Forge Version:  1.12.2-2529-7.0.0-BETA-2755
Forge: 14.23.1.2555
Total Economy Version:  1.7.1
JVM: 1.8.0_152
Server: Windows 10 Pro 
Permissions: LuckPerms Sponge 4.0.62

### Description of issue
Issuing commands in-game do not work and throw exceptions

Neither command with or without tab autocomplete and with or without decimal value
/adminpay smmmadden 10.00 dollar
/adminpay f098c794-f41a-4edd-a536-b638b26b748e 10.00 dollar
NoClassDefFoundError for AdminPayCommand.getTransactionResult
Error occurred while executing command: 

/balancetop - fails to show top balances
org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver:)V

Unable to get job details
/job info  - fails with same message as balancetop
/job info warrior - fails with same message as balancetop
/job warrior info - fails with same message as above 

just about all the commands are failing with the same type of exceptions as if they are not configured.  If it were due to lack of permissions, I should see a message I don't have permission, but this is not the case.

I've granted all the permission nodes and including the 5 for totaleconomy.job.farmer, miner, warrior, fisherman and lumberjack.  I can see that accounts.conf shows me as a farmer and messages that I'm being paid appear, but I also do not receive the money in my account.  It does appear also that the accounts.conf is missing the playername - only the uuid is present so perhaps it is related to this that most features are not working?

**Comment by MarkL4YG** [comment]
Make sure you're using the API-7 release first.

**Comment by smmmadden** [comment]
not sure what you mean by that.  I'm already using SpongeAPI version 7.

**Comment by smmmadden** [comment]
Never mind, I thought it would have been in the releases section, but found the downloads link that took me to another site where I could get it.  Will test that mod and see if the issues go away.

**Comment by smmmadden** [comment]
got the latest version for Sponge API 7 here: https://ore.spongepowered.org/Erigitic/Total-Economy/versions and using 1.7.1-API_7 everything is working fine now.  Closing.
Thanks!
