### ISSUE TITLE
seeds is mispelled & wheat overcharging in jobSets.conf

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#229]
Minecraft: 1.12.2
SpongeAPI Version: 7.0.0-SNAPSHOT-0ede943
Sponge Forge Version: 1.12.2-2529-7.0.0-BETA-2755
Forge: 14.23.1.2555
Total Economy Version: 1.7.1 and 1.7.1-API_7
JVM: 1.8.0_152
Server: Windows 10 Pro
Permissions: LuckPerms Sponge 4.0.62

Need to update minecraft:reeds to minecraft:seeds in jobSets.conf file.

"minecraft:reeds" {
       exp="5"
       money="7.50"
 }

Also the wheat seems to have a very high default value when it could be much lower (5.00) to be consistent with other blocks for farming.
            "minecraft:wheat" {
                exp="25"
                growthTrait=age
                money="50.00"
            }

**Comment by Erigitic** [comment]
"minecraft:reeds" is correct. 

Regarding the exp/money reward for wheat, this should and will probably be lowered in a future release.

**Comment by smmmadden** [comment]
thanks - you beat me to it.  I just found that reeds is sugar cane so this is correct.  I'm adding to jobSets the other farming options like melons, seeds, potato's and carrots for breaking and placing.

**Comment by Erigitic** [comment]
Set for release in 1.8.0: https://github.com/Erigitic/TotalEconomy/commit/eeb2c9c26309c6c8e7cb9e5e6342a2f2ec4376b1
