### ISSUE TITLE
Chest Shop default price to buy/setup $1000

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#231]
The wiki shows the default cost of $1000 to buy/create a chest shop.  Where is this defaulted and can it be changed?  I didn't see it in any of the four configs or the wiki pages.

**Comment by Erigitic** [comment]
Remake your main configuration file.

**Comment by smmmadden** [comment]
what setting is missing from the wiki page and the default totaleconomy.conf file to enable shops?

**Comment by Erigitic** [comment]
Here's the default configuration file with chest shops:

```
currency {
    dollar {
        currency-plural=Dollars
        currency-singular=Dollar
        default=true
        prefix-symbol=true
        startbalance="100"
        symbol="$"
        transferable=true
    }
}
database {
    enable=false
    password=""
    url="mysql://[IP]:[PORT]/[DATABASE]"
    user=""
}
features {
    jobs {
        enable=true
        notifications=true
        salary=true
    }
    moneycap {
        amount=10000000
        enable=false
    }
    shops {
        min-item-price=0
        max-item-price=1000000000
        chestshop {
            enable=true
            price=1000
        }
    }
}
language=en
save-interval=30
```

**Comment by smmmadden** [comment]
Thanks Eric - I've added the shop section to the configuration but the command is still invalid.  I also tried added totaleconomy.command.shop permission node (in case that was it), but the command (/shop buy) was still unrecognized.

**Comment by MarkL4YG** [comment]
You'll need to download the chest shop preview for this.

**Comment by smmmadden** [comment]
sorry, but no idea what that is.  There is nothing here https://github.com/Erigitic/TotalEconomy/wiki/Chest-Shops that I a) needed the configuration added (which I did add) or b) downloading anything other than the TotalEconomy plugin, hence why I'm confused. :-)

**Comment by MarkL4YG** [comment]
https://ore.spongepowered.org/Erigitic/Total-Economy/versions you'll want to download 1.8.0-dev3 at the moment.

**Comment by smmmadden** [comment]
that won't work with SpongeAPI 7.  Already tried that. :-)

**Comment by Erigitic** [comment]
As chest shops are still a work in progress, an API7 releases won't be added until after the full release. For now, the development releases are the only version.

**Comment by smmmadden** [comment]
okay thanks, I'll look into another mod for chest shops until it is ready for prime time.
