### ISSUE TITLE
Job Signs do not change color

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#232]
Job Signs do not work.  I tried [TEJOBS], [TE JOBS] and [JOBS} and none change the color of the sign and none change the job I'm in.  Is there a missing permissioins node to register the signs?
![image](https://user-images.githubusercontent.com/10309346/34429619-ab222672-ec28-11e7-8e46-f8a9c50f6e23.png)

**Comment by Erigitic** [comment]
It's case sensitive. Should be exactly `[TEJobs]`

**Comment by smmmadden** [comment]
Okay - got the signs to work properly now - they do not change color and the second line is changed to all lower cased characters but does work with both the left mouse click and right mouse click.

**Comment by Erigitic** [comment]
They should be changing color. I'll look into this.

**Comment by Erigitic** [comment]
Just tested this and the colors change on my end. What version of Total Economy and Sponge are you using?

**Comment by smmmadden** [comment]
I am using the 1.7.1-API_7.jar as I'm using Sponge 1.12.2-2555-7.0.0-BETA-2758. 

I also just now, updated my production server and re-placed the signs and the colors did change.  Though the color selection is very light.  Is there configuration to change the sign color so it uses the dark red and dark blue?
![image](https://user-images.githubusercontent.com/10309346/34457396-7b9ca228-ed7d-11e7-8837-95012e475e2b.png)

**Comment by Erigitic** [comment]
There is not, but I'll go ahead and adjust the colors to make it easier to see.

**Comment by smmmadden** [comment]
that would be great.  Thanks.

**Comment by Erigitic** [comment]
#235
