### ISSUE TITLE
place chest then /shop buy unknown command error

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#234]
Seems this command too is missing a permission or some other step not mentioned in the wiki page. I placed a single chest on the grown - pointed at it with the crosshair and /shop buy
In game chat returned: Unknown command. Try /help for a list of commands
Tried /help shop and hit enter and got no such command: shop

There is no permission node or command that is listed on wiki, so probably just an oversight..

**Comment by Erigitic** [comment]
You need to update your main configuration file. The easiest way to do this is to delete it and let it be remade when you start the server.

**Comment by smmmadden** [comment]
did I miss a page that stated to do this step or why it needs to be done at all?

**Comment by Erigitic** [comment]
When new options are added to the configuration files, the configuration file has to be remade. Total Economy doesn't, at the moment, check for and add missing configuration options. A note is added to releases stating that configuration files have to be remade or updated though.
