### ISSUE TITLE
Check that exp is correct after level/exp changes being introduced in 1.8.0

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#241]
In 1.8.0, experience points will be cumulative and no longer reset to 0 on leveling up. Something should be added to update the experience value for the user, if it is not correct, in order to avoid server owners and players from losing their job progress.

**Comment by MarkL4YG** [comment]
Could be included in #243 (as the proposal will have migrative code anyways) but that'd mean the release will be after the SQL changes.
What do you think?

**Comment by Erigitic** [comment]
I'm not expecting the SQL changes to be released with 1.8.0 due in part to the complexity of it, so this should be done beforehand.

**Comment by MarkL4YG** [comment]
As expected
