### ISSUE TITLE
Total Economy for 1.12.2 ?

### ISSUE THREAD

**Issue by DuFxonz** [Erigitic/TotalEconomy#242]
Hello, aare you developing this plugin for the 1.12.2 minecraft (7.0 Sponge API) ?

**Comment by smmmadden** [comment]
If you want the version for Sponge API 7.0.0, use the 1.7.1-API_7 download.  The 1.8.x are still running on version 6 of Sponge API.

![image](https://user-images.githubusercontent.com/10309346/34564039-3cadd1a0-f123-11e7-8170-822d02dae6d5.png)

**Comment by Erigitic** [comment]
Once 1.8.0 is released for API 6, work will begin on the API 7 version.

**Comment by ziceptor** [comment]
Chest Shops for api7. Looking forward to it!

**Comment by DuFxonz** [comment]
Thank you, I found before about those version 😄
