### ISSUE TITLE
Are Job Sets limited to 2 ?

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#245]
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a
SpongeForge: 1.12.2-2555-7.1.0-BETA-2842
Minecraft Forge: 14.23.1.2599
TotalEconomy: 1.7.1-API_7
Java: 1.8.0_162x64
O/S: Windows 10 Pro x64

### Description of issue:  When I add additional sets to a job (3 or more) then only the first two will pay.
CustomJob {
    require {
        job=""
        level=0
        permission=""
    }
    salary=25
    set=[
        ores,
        mobs,
        stones,
        earth
    ]
}
### Console errors
None on console, none in game.  Expectation is to be paid for any blocks in the job sets.
### Steps to reproduce
Add two more categories (stones including minecraft:stones and earth including minecraft:dirt)
The stones and dirt will not pay for break or place.  I tried with concrete, polished granite, granite, cobblestone and stone as well as break/place dirt.  I move them into the second set and remove the third/fourth sets and I get paid properly.

**Comment by Erigitic** [comment]
You seem to have a typo: `set` should be `sets`. Let me know if that fixes it for you.

**Comment by smmmadden** [comment]
actually, that was a direct copy/paste from the wiki page. lol  The config file is correct though using the plural form of set.

**Comment by MarkL4YG** [comment]
In that case the wiki has a typo. Good catch.

**Comment by Erigitic** [comment]
The typo is fixed. Sorry for the confusion.

**Comment by smmmadden** [comment]
sorry, but why would you close this out?  You fixed the typo on the wiki which is great, but the question remains unanswered. :-)

**Comment by Erigitic** [comment]
Oops, I thought you got it fixed:

> The config file is correct though using the plural form of set.

I'll reopen

**Comment by smmmadden** [comment]
no worries - easy to make.  Here is what I've configured so far in the jobsets  https://pastebin.com/f7bXVTpq

**Comment by Erigitic** [comment]
I copied your `jobsets` file and wasn't able to reproduce your issue.

Are you trying to destroy blocks that you place? If you are, that's why it isn't working, at least when it comes to breaking blocks. Total Economy has something in place that prevents experience and money from being rewarded when destroying a block placed by a player.

Another thing I saw, was that you don't have a job set for `earth`.

**Comment by smmmadden** [comment]
I tried both the place - got nothing, then break and got nothing.  I'm assuming there is a timer somewhere to prevent the place/break too soon apart from one another?  Earth, I had removed and just tried ores, concrete and stones.  I'm trying it again to see if I can repro again.

**Comment by Erigitic** [comment]
There's no timer in place that limits actions.

**Comment by Erigitic** [comment]
The `creator` of the block is stored within the block to explain it simply. All that is done, is when a block is broken we check to see if a block has a `creator`, and if it does, we do not reward anything. If it doesn't have a creator, which naturally spawned blocks don't, we reward the respective amount of experience and money.Placing of blocks is not affected by this at all. Only breaking blocks takes in account the `creator`.

**Comment by smmmadden** [comment]
got it working after downgrading sponge and forge.  They must have broken something along the way again.  Working fine now with Forge 2555 and Sponge 2842.  I had tried Forge 2599 up to 2605 (just came out) and none of them were working.  Guess I'll stick with the stable release for now.

That makes sense if we support only the place action, but since there could be both a place and a break in the same job for the same block - that's where looking at the creator doesn't really make sense.  I know we don't want to support cheaters placing/breaking to get double paid without some penalty.  That's where I think the timer (setting in config) makes sense to curtail anyone trying to cheat.  I make them wait 60 seconds which is well beyond most peoples happy wait time. :-)  At least I'd recommend thinking of that or not allowing both a place & break in the same jobset.

**Comment by Erigitic** [comment]
Glad you got it fixed.

Breaking and placing of the same blocks can be done in the exact same job set. It's just that you can't break blocks placed by other players. You could give out a reward when a user places `stone` and still give out a reward for when a user breaks `stone` within the same job. They just can't break stone they or another player placed.

It all depends on the use case though, and from the looks of it, you are wanting users to be able to break blocks they place, which unfortunately is not possible with Total Economy. A configuration option may be added later to leave the choice on this up to the server owner.

**Comment by smmmadden** [comment]
thanks that helps a lot.  :-)  Nice to know there is some grief prevention built into this - makes perfect sense!
