### ISSUE TITLE
Unable to purchase from my own shop

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#252]
SpongeAPI: 7.1.0-SNAPSHOT-06016f2
SpongeForge: 1.12.2-2611-7.1.0-BETA-2958
Forge Version:  14.23.2.2615
Total Economy Version:  1.8.0
Minecraft: 1.12.2

### Description of issue
I created a chest shop and wanted to test it out before rolling it out to users and when I clicked on the chest with the left mouse click, nothing happens.  Not sure if this is due to me being an admin (OP) or it has to do with the SpongeAPI difference between TE & Sponge.  I would have expected that I could click on the shop, but not charged because it would be coming and going to myself.  But at the least, I should be able to test that I get the item in my hand.

Did not find any permissions issues even with debugging turned on for LuckPerms. Everything looks okay from the above since nothing appears to be missing from totaleconomy perms or would otherwise not allow me to purchase from my own chest shop.

### Console errors
None

### Steps to reproduce
I created a chest shop by placing a chest on the ground.
Pointed at the chest and typed in /shop buy
Received confirmation of purchase.
Pointed at shop again and loaded the chest with (a stack of chests)
Typed in /shop stock 64 10.00
Received confirmation of setting the chest shop price
Left Clicked on the shop nothing happens on the game console or server console.
Turned on LuckPerms verbose to see if it were permissions issue, but it was not.
https://user-images.githubusercontent.com/10309346/37404428-3a5d288a-2768-11e8-9190-f4fdbed03c1e.png

### Related Configuration Files
Mods on the server:
![image](https://user-images.githubusercontent.com/10309346/37439277-c952e70e-27cd-11e8-900e-1c83570d598f.png)
If there is a specific config file you need to see, let me know.
Thanks -Steve

**Comment by Erigitic** [comment]
Are you opening the chest first and left clicking the items within it? Or are you trying to left click the actual chest block?

**Comment by smmmadden** [comment]
left clicking on the chest itself.

**Comment by Erigitic** [comment]
Left clicking on the chest isn't meant to do anything. You have to open up the chest and left click the items within it.

**Comment by smmmadden** [comment]
hmm okay, that's a bit different than I thought.  With chest protections, how would a user be able to open the chest to buy something if its locked and only allows them to buy from it?  I did open the chest and clicked on the item and it came into my hand, so that is working.  No confirmation other than I saw it in my inventory.

Single clicking one at a time when someone wants a stack isn't the quickest way to get them.  Perhaps when the player clicks, it would prompt a message in the chat window, with a message like: "How many xxxx would you like to buy at $10.00 each? 
This way the player can choose an entire stack in one click.  What do you think?

**Comment by MarkL4YG** [comment]
You don't need to protect the shop chests. TE handles that.
I believe to have suggested something like shift+click on a stack to buy the whole thing and ctrl+click for a stack. Either way this would be my suggestion if it's not like this at the moment.

**Comment by Erigitic** [comment]
I want to avoid making purchasing items from a shop a long process. So I'd prefer to not prompt the user to type in how much they want to buy after clicking the item. This would mean the chest would have to be closed and reopened as you can't send messages with an inventory open. 

Shift clicking or ctrl clicking items will be added to purchase stacks in a later update. I meant to add that in 1.8.0. I'll create another issue for this.

**Comment by smmmadden** [comment]
Thanks - I've confirmed:
**Shift + Left Click** does nothing
**Ctrl + Left Click** buys one item
**Left Click** buys one item

**Suggested behavior:**
**Shift + Left Click** buys everything shown in that square (whatever that current stack total is - 1-64) that was selected to buy.
**Ctrl + Left Click** buys the maximum available for that block type (e.g. signs is 16, tools like spade, axe, etc are 1 and most other blocks could be 64 or an oversized stack size of 128 if configured).
**Left Click** buys one item
