### ISSUE TITLE
Total Economy crashes (at the restart) after installing GriefProtection

### ISSUE THREAD

**Issue by fsgmhoward** [Erigitic/TotalEconomy#255]
Sponge Version:  1.12.2-2611-7.1.0-BETA-2931
Forge Version:  1611
Total Economy Version:  1.8.0

### Description of issue
I have done something in the steps to reproduce (see below).
It seems to be a problem relating to GP as well. However when I removed all GP's jar, the problem persists. It seems that GP has changed the property of the chest. Since it is the TE crashing, I just open an issue here.

### Console errors
At the final stage of loading:
https://hastebin.com/nefibiwopo.hs

After user connects:
https://hastebin.com/ubohonereq.hs

Crash report:
https://hastebin.com/hoxavakuze.sql

### Steps to reproduce
1. Set up a chest shop
2. Stop server, installed GriefProtection build 504, restart server, everything works ok
3. Stop server, delete GP b504, replace with GP b555, restart server, connect from client, crashed
4. Stop server, delete GP b555, replace with GP b560, restart server, connect from client, crashed
5. Stop server, delete all GP's jar, restart server, connect from client, crashed
6. Stop server, using back GP b504, restart server, connect from client, crashed
6. the above crash reports/logs are obtained at step 5

**Comment by Erigitic** [comment]
Have you tried replacing the Total Economy jar?

**Comment by fsgmhoward** [comment]
@Erigitic I checked the checksum of the file one on my disk and the one released, they have the same checksum.

Maybe this is a permission problem, but my server is booted under Admin permission. I tried to delete the file and download again, the problem persists.

Updating Sponge to 1.12.2-2611-7.1.0-BETA-2970 does not fix this problem.

**Comment by Erigitic** [comment]
Let's move future discussion on this issue to #262
