### ISSUE TITLE
Total Economy Job Signs

### ISSUE THREAD

**Issue by Navydead** [Erigitic/TotalEconomy#257]
Sponge Version:  SpongeForge 1.10.2-2477-5.2.0-BETA-2793
Forge Version:  
Total Economy Version:  1.6.0 

I can create a Sign with each Job (Color is changing), but if someone clicks on the sign (Admin or User) it say's "[TE] Sorry, this job does not exist

None exist

Im not sure if its because of the "Older Sponge API Version "

**Comment by MarkL4YG** [comment]
we're currently at 1.8.0. I suspect this may have been fixed already.

You may also try the preview for the backport in a testing environment.

**Comment by Erigitic** [comment]
I'm not able to recreate this issue on the latest release, and we no longer support API 5. I'd recommend updating to the API 6 release I just uploaded to the Ore page if possible: https://ore.spongepowered.org/Erigitic/Total-Economy.
