### ISSUE TITLE
Chinese message configuration

### ISSUE THREAD

**Issue by 892279645** [Erigitic/TotalEconomy#264]
# AdminPay Command
"command.adminpay.remove.recipient"="&7你的&6{amount}&7被&6{sender}&7移除&7。"
"command.adminpay.remove.sender"="&7你移除了&6{recipient}&7的&6{amount}&7。"
"command.adminpay.send.recipient"="&7你从&6{sender}&7收到了&6{amount}&7。"
"command.adminpay.send.sender"="&7你给&6{recipient}&7发送了&6{amount}&7。"

# Balance Command
"command.balance.default"="&7元: &6{amount}"
"command.balance.other"="&7{currency}元: &6{amount}"

# Job Command
"command.job.current"="&7当前工作：&6{job}"
"command.job.exp"="&7{job}经验: &6{curexp}/{exptolevel}经验"
"command.job.level"="&7{job}等级: &6{curlevel}"
"command.job.set"="&7工作设置为: &6{job}"

# Pay Command
"command.pay.recipient"="&7你从&6{sender}&7收到了&6{amount}&7。"
"command.pay.sender"="&7你给&6{recipient}&7发送了&6{amount}&7。"

# Set Balance Command
"command.setbalance"="&7你将&6{recipient}&7的余额设置为&6{amount}&7。"

# View Balance Command
"command.viewbalance"="&7{recipient}的余额: &6{amount}"

# Jobs
"jobs.addexp"="&7你在&6{job}&7工作中获得了&6{exp}经验&7。"
"jobs.levelup"="&7恭喜，你现在是&6{level}&7级&6{job}&7。"
"jobs.notify"="&6{amount}&7已经存入你的余额。"
"jobs.salary"="&7你的工资&6{amount}&7已到账。"
"jobs.sign"="&7职业变更为：&6{job}"
"jobs.toggle"="&7选项切换成功。"

# Notifications
"notifications.on"="&7通知现在&a开启"
"notifications.off"="&7通知现在&c关闭"

# Shop Command
"command.shop.stock.success"="&7你添加了 &6{quantity}x{item} &7价格为&6{price}&7."
"command.shop.stock.insufficientitems"="&C你没有足够的东西出售！"
"command.shop.stock.noslots"="&C这个商店已经有足够的物品！"
"command.shop.buy.success"="&7你成功的购买了一个商店"
"command.shop.buy.notowner"="&C你没有箱子！"
"command.shop.buy.alreadypurchased"="&C这个箱子已经被购买了！"
"command.shop.buy.notempty"="&C只有这个箱子是空的，你才能得到它！"
"command.shop.buy.insufficientfunds"="&C资金不足！这个商店花费 {price}！"
"command.shop.buy.doublechest"="&C大箱子是不能被购买！"

# Shops
"shops.purchase.noroom"="&C你没有足够的空间购买这个物品！"
"shops.purchase.insufficientfunds"="&C资金不足！"
"shops.remove.notowner"="&C你不能拥有这个商店！"
"shops.remove.stocked"="&C你不能移除还在出售物品的商店！"

**Comment by MarkL4YG** [comment]
Now that's surprisingly exotic ^^.  (Meaning in a positive way of course)

Let's see what Eric thinks about that 😄

**Comment by Erigitic** [comment]
I'd love to get this added in. Would you mind submitting a pull request with these changes? Here are instructions on how to go about that: https://github.com/Erigitic/TotalEconomy/blob/develop/CONTRIBUTING.md#contributing-translations

**Comment by 892279645** [comment]
I don't know much about GitHub.I don't know how to submit a pull request......
emmm......Of course you can add this.but I don't know what to do.Maybe I should learn it recently.

**Comment by Erigitic** [comment]
No problem. I can take care of that, unless you'd prefer to do it yourself in order to learn the process.

**Comment by MarkL4YG** [comment]
I would highly recommend you trying the process :)
This change is small and doesn't involve possible conflicts so it's perfect for your first real pull request ^^

**Comment by Erigitic** [comment]
Added here: https://github.com/Erigitic/TotalEconomy/pull/292
