### ISSUE TITLE
Extreme /baltop lag.

### ISSUE THREAD

**Issue by Corcustos** [Erigitic/TotalEconomy#270]
Sponge Version:  1.12.2-2611-.7.1.0
Forge Version:  1.12.2-14.23.2.2611
Total Economy Version:  1.8.0

### Description of issue
Everyone time I run /baltop, it lags the server severely. I'm not entire sure what's going on. We do have a lot of accounts, but I've used an old version of totaleconomy on an old version of pixelmon a while ago and I remember it working fine. Should I delete old accounts...?

### Console errors
There aren't any actual console errors pertaining to this, It just makes the server lag behind. This is what's in the console after I do /baltop and before people start connecting again. https://pastebin.com/v8jhPeTy

### Steps to reproduce
All I have to do is run /baltop.

### Related Configuration Files
totaleconomy.conf:
https://gist.github.com/Corcustos/51555198d9e372841a52cb710c3adee6

accounts.conf
https://gist.github.com/Corcustos/a6a2571711ee832f9eaf030fcf89de80

**Comment by MarkL4YG** [comment]
I normally would ask you to check whether or not this persists after changing to a database for account storage but as of now the baltop command does not support that storage type. ( #251 )
And automatic data migration is still in the works too ( #243 )

How big is your ``accounts.conf`` at the moment? (The attached one seems to be the wrong file)

**Comment by xion87** [comment]
for me it crash all player when /baltop is used and salary is not received

**Comment by MarkL4YG** [comment]
@xion87 Could you provide a crashlog and your ``accounts.conf`` please. I would like to take a look at your issue too.

**Comment by xion87** [comment]
there is no crash, only absurd lag that cause disconection, players will keep to receive "cannot pay your salary"
Here i attached both conf and accounts
[data (2).zip](https://github.com/Erigitic/TotalEconomy/files/1995525/data.2.zip)

**Comment by MarkL4YG** [comment]
@xion87 That salary thing is a different issue. Maybe open another one for that.
  
---
At 355 lines and 5

**Comment by xion87** [comment]
what At "355 lines and 5"

**Comment by Erigitic** [comment]
Baltop does not work with MySQL yet. This is something that will and should be added later. I'm not sure why it would be lagging with only 71 accounts, but I'll look into it.

**Comment by xion87** [comment]
what you mean?

**Comment by Erigitic** [comment]
Which part are you confused about?

**Comment by xion87** [comment]
"you mind updating the gist for your accounts.conf"

**Comment by Erigitic** [comment]
The gist you supplied in the original post (https://gist.github.com/Corcustos/e5a7ad371ab70546342aea9692d9a194) looks incorrect. Would you mind creating a new gist with the actual contents of your `accounts.conf` file?

**Comment by xion87** [comment]
@Corcustos do the gist, not me

**Comment by Erigitic** [comment]
@xion87 Sorry about that, just realized you weren't the OP.

**Comment by Erigitic** [comment]
But I guess it applies for you as well. Please post your configuration files in a gist (https://gist.github.com/). I'd prefer to not download anything. Thanks.

**Comment by xion87** [comment]
https://gist.github.com/xion87/2b50846c1b79a2a7b0e3c631cb781bbe

**Comment by MarkL4YG** [comment]
> There are 2,719 accounts

> you have about 2,872 accounts

That amount of accounts should definitely be stored in a database imo.
Remember that a safe does write the whole file each time.

**Comment by MarkL4YG** [comment]
@Erigitic if you want to I can submit a PR for the baltop SQL support today. Shouldn't be that much to add to the code.  
And after the refactor (if accepted) it'll be different code anyways.

**Comment by Erigitic** [comment]
If you have the time I'd appreciate that.

**Comment by MarkL4YG** [comment]
I had some troubles getting my testing environment running but here you go (will tell you about that in Gitter).  

@Corcustos @xion87 would you two mind cloning your production environment onto a test-instance so we can see whether or not this changes work out?
I would create a testing release for you to try out. Oh and I'll have to include an importer for your flat file data too if I remember correctly, right @Erigitic ?

**Comment by Erigitic** [comment]
To import the `accounts.conf` data into a MySQL table? If so then yes.

**Comment by Corcustos** [comment]
By cloning my workspace and running a test-instance I'm assuming you mean copying my server and running it on a test node? I'm a little confused, sorry.

**Comment by MarkL4YG** [comment]
Yes indeed.

**Comment by MarkL4YG** [comment]
It only needs to handle your single user.
You can delete nearly everything.

Only the playerdata (for UUID matching) and TotalEconomys data needs to be preserved.

**Comment by Corcustos** [comment]
So all I need to run is spongeforge, forge, and totaleconomy+files

**Comment by MarkL4YG** [comment]
Yes

**Comment by xion87** [comment]
so all this stuff for a convertion command?

**Comment by MarkL4YG** [comment]
What do you mean by that?  
Of course we're trying to test any feature we develop. And as you two had issues we'd like to see whether or not those are now fixed.

**Comment by xion87** [comment]
sure why not :)

**Comment by MarkL4YG** [comment]
I decided to write a helper plugin for import/export to the current database schema.  
Maybe this'll help more people than just the two of you for testing.

**Comment by xion87** [comment]
can you share?

**Comment by MarkL4YG** [comment]
Of course I'll do that. As soon as it can be used ;)

**Comment by xion87** [comment]
Any news? Also i noticed some bad performance on my server
https://timings.aikar.co/?id=76b5a571388c4645ac9ee61e5324794d

**Comment by MarkL4YG** [comment]
That can indeed happen with that many accounts.

I'm just finishing some stuff for the import.

Will be creating a repository and provide links when done :)

**Comment by MarkL4YG** [comment]
Hey there, I was busy moving during the last two days but I've now created a repository for the helper plugin.
There's a (hopefully) usable release candidate available for you to test out in said testing environment.

Repository: https://github.com/MarkL4YG/TE-SqlHelper  

Remember that this requires you to configure a valid database connection in your ``totaleconomy.conf``.
(If you enable the connection or not is not important as only the connection information is used.)

**Comment by xion87** [comment]
I have to enable sql database before to use the command?

**Comment by MarkL4YG** [comment]
@xion87 you have to configure it in the config of TotalEconomy. ``enable`` can stay ``false``.  
But you'll have to have a database server and a user for that database configured of course.

**Comment by xion87** [comment]
ok i gonna give a try tommorow ;)

**Comment by xion87** [comment]
Is importing nothing
[09:05:53] [Server thread/INFO] [nucleus]: Server ran the command: /te-helper import
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Reading TE configuration...
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Initializing database connection...
> [09:05:53] [pool-4-thread-1/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
> [09:05:53] [pool-4-thread-1/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Collecting currencies...
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Collecting jobs...
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Wiping tables...
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Generating tables...
> [09:05:53] [pool-4-thread-1/INFO]: [ImportWorker]Importing data... (this may take a moment)
> [09:05:54] [pool-4-thread-1/INFO]: [ImportWorker]Import successful!
> [09:05:54] [pool-4-thread-1/INFO]: [ImportWorker]Worker exiting.

**Comment by MarkL4YG** [comment]
Please verify that your ``accounts.conf`` actually contains data to import.

**Comment by xion87** [comment]
The file accounts.conf is still here

**Comment by MarkL4YG** [comment]
I've not added more verbose output on "DEBUG" level.  
You may download the ``TESqlHelper-0.1.1-TE1.8.1.jar`` from the same release/repo.  
  
Be aware that this output may not show these messages as they are logged to ``DEBUG``.  
The log file however should contain them.  

As the behavior did not change you'll notice that the tables will still be empty. Please upload your server logs afterwards as a gist and link it here so I can take a closer look at what's happening.

**Comment by xion87** [comment]
https://gist.github.com/xion87/14d59e0da3c4b3580e30c544bb4d37d8 
there are no errors and is importing all accounts

**Comment by xion87** [comment]
nvm i was looking the wrong table "virtual_account" instead "accounts", all accounts are imported, btw do you mind to add a sql prefix? like te_

**Comment by xion87** [comment]
when i do /baltop it trow error (i am using database now)
https://gist.github.com/xion87/c31f5bf044afd2d558151795878c77c3

**Comment by MarkL4YG** [comment]
@xion87 currently on my way home. Will investigate once arrived.

And I'm not quiet sure if TE already supports prefixes.

I'll also take a look into that.

**Comment by MarkL4YG** [comment]
@xion87 Don't know how I didn't notice that on the fly. Your exception is of course due to TE not having released the fix for ``baltop`` not supporting databases yet ^^``.  
@Erigitic You may wanna do a hotfix release for that.  

As for the prefixes: Please open another issue as it will be a feature request and is currently not supported.  
I recommend just dedicating a database to TotalEconomy and you should be fine.

**Comment by Erigitic** [comment]
@xion87 Are you using Total Economy 1.8.1 that was released yesterday?

**Comment by MarkL4YG** [comment]
huh, I didn't even notice. Well - that version should do the job.

**Comment by TonyoBlaster** [comment]
Maybe an update ?
