### ISSUE TITLE
Console error when using job sign.

### ISSUE THREAD

**Issue by pigneedle** [Erigitic/TotalEconomy#275]
Sponge Version:  1.12.2-2655-7.1.0-BETA-3064
Forge Version:  14.23.3.2655 
Total Economy Version:  1.8.1

### Description of issue
Console error when using job sign. The job still switches correctly.

### Console errors
[Console error](https://gist.github.com/pigneedle/362ba26c2eb22c320b0c6b9a31c43a25)

### Steps to reproduce
Place a job sign, then use it.

### Related Configuration Files
[Log](https://gist.github.com/pigneedle/3f128eccbd2d21a0cb2b00a416bce098)

**Comment by MarkL4YG** [comment]
I assume this is for #274 ?  
I'm currently setting up my workspace after having to reset my PC - will check in half an hour or so.  
Also you may want to attach the log message using a Gist.

**Comment by pigneedle** [comment]
It is a separate issue.

**Comment by MarkL4YG** [comment]
Oh, nevermind in that case.  
Still - please attach your logs so we can see what Sponge's telling us.

**Comment by Erigitic** [comment]
Seems like the messages file is not being loaded. Is there a messages_en file in the config folder? I also noticed an issue with the salary task, which is probably unrelated to this issue.

**Comment by MarkL4YG** [comment]
Maybe a syntax error. The current version of TE doesn't explicitly log any exception. There should be a warning about it failing to load/create the messages file in that case.

**Comment by pigneedle** [comment]
I can confirm there was a messages_en file in the config folder when I was receiving errors.

**Comment by Erigitic** [comment]
Would you mind creating a gist containing the contents of your `jobs.conf`

**Comment by Erigitic** [comment]
I belive this line is causing it: https://github.com/Erigitic/TotalEconomy/blob/17a7ed1ae5b30ee471b68219f24636000be833bd/src/main/java/com/erigitic/jobs/TEJob.java#L57. The job is null.

**Comment by MarkL4YG** [comment]
I don't really think so honestly. That variable is used for the requirement and ``null`` as job requirement means ``not set`` therefore is a valid value.

**Comment by MarkL4YG** [comment]
Might be that some place may miss out on a check for that though.

**Comment by Erigitic** [comment]
The job string is being converted to lowercase and throwing an NPE in the getJobLevel function according to the log: https://github.com/Erigitic/TotalEconomy/blob/17a7ed1ae5b30ee471b68219f24636000be833bd/src/main/java/com/erigitic/jobs/JobManager.java#L514

So the job name being passed in must be null.

That function is being called here and the required job name is being passed in: https://github.com/Erigitic/TotalEconomy/blob/17a7ed1ae5b30ee471b68219f24636000be833bd/src/main/java/com/erigitic/jobs/JobManager.java#L675

Somewhere the required job is being set to null or never set in the first place and the code snippet I posted above seems to be the only place where that would occur. I'll test this out on my end a bit later this week to make sure.

**Comment by Erigitic** [comment]
I see what you're saying now @MarkL4YG. If the job name is `null` there shouldn't be a job requirement. @pigneedle What job is set on the sign that's throwing the error?

**Comment by pigneedle** [comment]
Any of them.

**Comment by Erigitic** [comment]
I know it's been a long time, but is this still occuring @pigneedle?

**Comment by pigneedle** [comment]
I will have to check when I have time.

**Comment by pigneedle** [comment]
I am no longer receiving this error.
