### ISSUE TITLE
 Buy / Sell Objects

### ISSUE THREAD

**Issue by BaentyServ** [Erigitic/TotalEconomy#276]
Hello,
I want to sell and buy items in a shop, with sponge server 1.10.2. I do not know how to set prices, and at the same time, how to differentiate prices from sales and purchases. If possible, I want to have an example file. And what is the command.
Cordially

**Comment by Erigitic** [comment]
Chest shops only work with Total Economy version 1.8.0 and newer. The oldest Miencraft version chest shops are made to work on is 1.11.2.

**Comment by BaentyServ** [comment]
So what is the totaleconomy folder in the "config" of the server?

**Comment by MarkL4YG** [comment]
Euh... The configuration folder?

**Comment by Erigitic** [comment]
I don't believe there is an issue here anymore. If I'm wrong, please let me know and I'll reopen. Thanks.
