### ISSUE TITLE
permission of job doesn't work

### ISSUE THREAD

**Issue by 276562578** [Erigitic/TotalEconomy#277]
Sponge Version:  3148
Forge Version:  2705
Total Economy Version:  1.8.1

### Description of issue
the job 'miner' need permission 'totaleconomy.job.miner', but it doesn't work. people still can obtain money even if i set user permission to false using 'luckperms' that is a sponge permission plugin.
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by Erigitic** [comment]
Please provide your `jobs.conf` file in a gist.

Are players able to do `/job set miner` even without the permission?

**Comment by 276562578** [comment]
jobs.conf
`jobs {
    unemployed {
        require {
            job=""
            level=0
            permission="totaleconomy.job.unemployed"
        }
        salary=1
        sets=[
            mobs
            fish
            ores
            lumberjackSet
        ]
    }
}
salarydelay=300`

and permission now is
`totaleconomy.command.job (true)
totaleconomy.job.unemployed (false)`

if i set `totaleconomy.command.job (false)` people can't use `/job`, but still can obtain money

**Comment by MarkL4YG** [comment]
``unemployed`` is the defaul/fallback job. It does not make sence trying to require a permission for that.

**Comment by 276562578** [comment]
change it to other name doesn't work either.

**Comment by Erigitic** [comment]
This issue has been quiet for sometime so I'm going to close it. If you still need help, please leave a comment and I'll reopen. Thanks.
