### ISSUE TITLE
Missing permission node for chest shop

### ISSUE THREAD

**Issue by vMpee** [Erigitic/TotalEconomy#278]
Sponge Version:  spongeforge-1.12.2-2705-7.1.0-BETA-3158.jar
Forge Version:  3158
Total Economy Version:  1.8.1

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by Erigitic** [comment]
Here are the permissions for the shop commands:

`totaleconomy.command.shop.stock`
`totaleconomy.command.shop.buy`

I'll get these added to the wiki right now.

**Comment by Erigitic** [comment]
@vMpee Let me know if those permissions work for you. Thanks.

**Comment by vMpee** [comment]
No, they still do not work. I gave the permissions to specifically me, and as an admin, I still don't have permissions to use it.

**Comment by MarkL4YG** [comment]
> as an admin

That does sound more like a general issue with your setup in that case. If you already have wildcard permissions your permissions plugin should not report any permission as missing.

**Comment by vMpee** [comment]
@MarkL4YG Yeah, it works when I use the wildcard, but I don't want to give every player the perms to everything. 

I'm saying that the perms @Erigitic gave still didn't let my players use chest shop

**Comment by MarkL4YG** [comment]
As the two commands ``buy`` and ``stock`` are children of the shop command you'll also need to grant them ``totaleconomy.command.shop``. 
_Note: This will be an implicit wildcard for both commands in the permission API defined by Sponge. But implementation of this is still up to the plugin implementing the API._  
Luckyperms for example has got a toggle in the config to revert to bukkit behavior where only ``*`` wildcards were allowed. ( See #205 )

**Comment by Erigitic** [comment]
Closed in favor of https://github.com/Erigitic/TotalEconomy/issues/205. Continue discussion there. Thanks.
