### ISSUE TITLE
TotalEconomy not being loaded by forge

### ISSUE THREAD

**Issue by martmists** [Erigitic/TotalEconomy#280]
Sponge Version: 1.12.2-2705-7.1.0-BETA-3171
Forge Version: 14.23.4.2707
Total Economy Version: 1.8.1

### Description of issue
TotalEconomy, residing in `mods/TotalEconomy.jar`, is not being loaded by SpongeForge

### Console errors
None

### Steps to reproduce
Download the ATM3 Server files, SpongeForge and TotalEconomy, add them in the `mods` folder and launch the server.

### Related Configuration Files
None

**Comment by MarkL4YG** [comment]
Server logs or it didn't happen :P

Please attach your logs in a gist so we can see if SF wants to tell us something.

**Comment by Erigitic** [comment]
Since it's been over a month without any activity, and no logs were provided, I'll be closing this issue. If you still need help with the issue, please let me know and I'll open it back up. Thanks.
