### ISSUE TITLE
Cant get payday or set any job.

### ISSUE THREAD

**Issue by YumaYamamoto** [Erigitic/TotalEconomy#288]
Sponge Version:  spongeforge-1.12.2-2705-7.1.0-BETA-3206
Forge Version:  Latest
Total Economy Version:  TotalEconomy-1.8.1

### Description of issue
I cant set any job it says: Job dont exist but it exist.
Also I dont get any payday...
http://i.epvpimg.com/1ZoFbab.png

### Console errors
Cant find any.

### Steps to reproduce
Just translated some lines to German language instead of English. And changed the job names

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

Dont get how this works.

**Comment by MarkL4YG** [comment]
Probably some special character didn't get the escapes it needs.
I can tell you what to do if you attach your server logs in a gist  (which is why that step is part of the issue template) ;)

**Comment by YumaYamamoto** [comment]
Well but how, I dont get that gist thing... :D

**Comment by YumaYamamoto** [comment]
Could it be possible because I did change the currency symbol to ¥ instead of $ or €?

**Comment by MarkL4YG** [comment]
And the symbol should be supported as Java/MC uses UFT-8 which does support this sign. :thinking:  
Not sure about the HoconConfigLoader though. Should check about that.

**Comment by YumaYamamoto** [comment]
Yeah it is the symbol... I removed it and replaced it with $ to test and it worked again... even with the full translation to German. Could you fix that? I did remove the symbol now completly and did put it into the language file manually :)
