### ISSUE TITLE
Jobs arent working anymore since we use mysql

### ISSUE THREAD

**Issue by YumaYamamoto** [Erigitic/TotalEconomy#289]
Sponge Version:  spongeforge-1.12.2-2705-7.1.0-BETA-3206
Forge Version:  Latest, I dont really know, its just named forge.jar in the server folder.
Total Economy Version:  TotalEconomy-1.8.1

### Description of issue
I use a mysql databank since yesterday and the jobs dont work now anymore...

### Console errors
None

### Steps to reproduce
Using mysql database

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue
https://gist.github.com/YumaYamamoto/05f9e3eb446b8701eaf65eb4d8a81306

**Comment by MarkL4YG** [comment]
Please describe in which way jobs don't work anymore. And please attach your server log using a gist.

**Comment by MarkL4YG** [comment]
> No files  ¯\_(ツ)_/¯

**Comment by YumaYamamoto** [comment]
@MarkL4YG was ist nun das Problem? :)

**Comment by MarkL4YG** [comment]
@YumaYamamoto Let's keep this international, shall we? ;)
Please attach you server log to the gist as it currently is empty.

If you want to talk in German, feel free to contact me via Gitter.
I'll need the server logs anyways though.

**Comment by MarkL4YG** [comment]
As far as I understood over Gitter this issue has been resolved and can be closed.
