### ISSUE TITLE
NPE on SqlManager.java creating table with Postgres

### ISSUE THREAD

**Issue by devthedevel** [Erigitic/TotalEconomy#290]
Sponge Version:  spongeforge-1.12.2-2705-7.1.0-BETA-3206
Forge Version:  14.23.4.2705
Total Economy Version:  1.8.1

### Description of issue
Cannot connect to a Postgres database. I get an NPE on SqlManager.java:78, which makes me think that the DataSource is not able to get a connection to the database.

### Console errors
See attached Gist.

### Steps to reproduce
Load above versions with below config.

### Related Configuration Files
https://gist.github.com/devthedevel/bf201b658765d7121787c771904b00c8

**Comment by MarkL4YG** [comment]
Since [this](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/sql/SqlManager.java#L78) is the line in question I would say the ``DataSource`` initialization failed. So please provide your full server log for us to investigate.

**Comment by devthedevel** [comment]
I have updated my gist above. Note that I since dropped Postgres and switched to MySQL instead. Also that I'm trying to connect from localhost now. I'm sure that my privileges are set correctly, and I tested that I can actually connect with the user on localhost.

**Comment by devthedevel** [comment]
Ok so I'm a silly goose. Turns out that the special characters in my password was preventing Sponge from connecting to the database. I just changed the password to alphanumeric and it worked!
