### ISSUE TITLE
issue/[Chinese] translate

### ISSUE THREAD

**Issue by JoshuaCHZ** [Erigitic/TotalEconomy#291]
Sponge Version:  
Forge Version:  
Total Economy Version:  

### Description of issue
Chinese translation
### Steps to reproduce
I will translate ````     Sorry I don't know how to use GitHub  this is my first time
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

REPORT

- [x] Now we have a problem;  
When I was translating, it looks good.
![image](https://user-images.githubusercontent.com/37192210/42919278-3806aa32-8b65-11e8-8d3c-2454b0bc4f3e.png)
but when I build it and check the GitHub desktop it just displays some random code.
![image](https://user-images.githubusercontent.com/37192210/42919320-6b3e013e-8b65-11e8-86f4-3cfab1782891.png)
in-game-test as well

### fixed
![image](https://user-images.githubusercontent.com/37192210/42920453-c93cd8d2-8b6a-11e8-9462-ef816729749e.png)

- [x] In game test 
![image](https://user-images.githubusercontent.com/37192210/42920439-b6d3d20e-8b6a-11e8-94a5-ebc9d9ca4d10.png)

SUCCESS
![image](https://user-images.githubusercontent.com/37192210/42922298-1ea7d0e8-8b74-11e8-9962-e6a3591740d2.png)
![image](https://user-images.githubusercontent.com/37192210/42922546-1ea6bbf8-8b75-11e8-93a5-0b2e5be4dcd2.png)

ready to pull

**Comment by Erigitic** [comment]
No need to apologize :) For Chinese, I believe the locale for it is `zh`. So be sure to name the translated messages file `messages_zh.conf`. Once you are done translating the file, please be sure to test it in game to make sure the messages look correct.

Also, if it's easier, once you are done you can just send the file in a Gist (https://gist.github.com/) instead of submitting a pull request. Though I do highly recommend learning how to do pull requests. And if you have any questions, we'd be more than happy to help you out. Thanks!

**Comment by JoshuaCHZ** [comment]
I think I finished translate, and, how can I test it in game. Do I need to
run the build again?
thanks😀😀

**Comment by JoshuaCHZ** [comment]
Now we have a problem;  
When I was translating, it looks good.
![image](https://user-images.githubusercontent.com/37192210/42919278-3806aa32-8b65-11e8-8d3c-2454b0bc4f3e.png)
but when I build it and check the GitHub desktop it just displays some random code.
![image](https://user-images.githubusercontent.com/37192210/42919320-6b3e013e-8b65-11e8-86f4-3cfab1782891.png)
in-game-test as well

**Comment by JoshuaCHZ** [comment]
When I do edit in eclipse the file encode is UTF-8 but when I do server test, the language file turn into GB2312

need some help with this ```

**Comment by JoshuaCHZ** [comment]
I'm ready to pull. but it says I don;t have the permission 
![image](https://user-images.githubusercontent.com/37192210/42929212-7f7591f8-8b8d-11e8-8af2-404cfa6c07a7.png)
