### ISSUE TITLE
About parameters

### ISSUE THREAD

**Issue by lichenglin19901123** [Erigitic/TotalEconomy#297]
Sponge Version:  1.12.2
Forge Version:  2705
Total Economy Version:  
1.8.1
### Description of issue
What parameters are available in this plugin? I need the parameters and working parameters of the economic leaderboard. For example https://minecraft.gamepedia.com/Statistics in this website
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Euh... I'm not sure what you mean by "parameters". Could you describe what you're trying to do? 😕

**Comment by Erigitic** [comment]
This issue has been quiet for quite some time so I'm going to close it. If you still need help, please feel free to post another comment here. Thanks.
