### ISSUE TITLE
Adding Jobs via command block does nothing

### ISSUE THREAD

**Issue by ehmitchell3** [Erigitic/TotalEconomy#299]
Sponge Version:  7.1.0-snapshot-7105dfc
Forge Version:  1.12.2-14.23.4.2705-universal.jar
Total Economy Version:  1.8.1

Hey all,

I just wanted to know if there were any special commands or something in order to set jobs via command block. I'm using "/job set lumberjack @p[x=###,y=##,z=###,r=#]", as well as "/job set lumberjack @p", and there's no change.

Any thoughts?

Thanks!

**Comment by MarkL4YG** [comment]
Interessting. Have you verified the command as working using your client?
Otherwise I would say "@p" is not resolved to a player by Sponge when passing the command to TE ...

**Comment by ehmitchell3** [comment]
@MarkL4YG: Many apologies, it was four hours of banging my head against the wall. Console block seems to work given the "/job set <job> @p[coords]" command.

One more question--how do I change what shows up in the available jobs when someone types "/job"?

Thanks!

**Comment by MarkL4YG** [comment]
You can edit the available jobs in your ``jobs.conf``. Same goes for adding/removing jobs.  
What actions provide rewards can be configured in your ``job-sets.conf``.  
If you edit them I would personally recommend keeping the original as a copy for comparison reasons.

**Comment by ehmitchell3** [comment]
Thanks, Mark!

If you want, I can message you the jobs file I have if you'd like to include some of the Twilight forest mobs in your conf file.

Thanks again.
