### ISSUE TITLE
Suggestion - PickPocketing?

### ISSUE THREAD

**Issue by ThomasAunvik** [Erigitic/TotalEconomy#3]
Pickpocketing is normal irl. Why not in MC too? Hold an special item or not and sneak right-click and you get 1$. You can only do it 5 times pr player every 10 min. so youll steal 5$ pr player every 5 minutes. This must be a great idea.

**Comment by Erigitic** [comment]
I will keep this in mind and see how I can implement this as a job possibly. Thanks for the suggestion.
