### ISSUE TITLE
How to use Pixelmon Reforged currency for Total Economy? 

### ISSUE THREAD

**Issue by Bayron2304** [Erigitic/TotalEconomy#301]
Sponge Version:  1.12.2-2705-7.1.0
Forge Version:  1.12.2-14.23.4.2705
Total Economy Version:  1.8.1

### Description of issue

How can I set the currency to use to PokéDollars from the Pixelmon Reforged mod? I know this isn't really an issue or contribution but maybe some one else is having the same problem.

Right now I have 2 currencies, the one from Pixelmon Reforged called 'PokéDollars' and the default one from TE. How can I make it so TE uses those PokéDollars instead of the default currency? Beware, complete coding noob here. 

Thanks in advance.

### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by Erigitic** [comment]
Are you using the Pixelmon economy bridge? https://pixelmonmod.com/wiki/index.php?title=Economy_Bridge

**Comment by Erigitic** [comment]
I'm going to assume this was fixed by installing the economy bridge. If not, please let me know and I'll reopen. Thanks.
