### ISSUE TITLE
Total Economy mysql leak

### ISSUE THREAD

**Issue by xion87** [Erigitic/TotalEconomy#302]
Sponge Version:  3361
Forge Version:  2705
Total Economy Version:  1.8.1

### Description of issue
I noticed Totaleconomy create a lot of connection to database (around 50 connections)
![image](https://user-images.githubusercontent.com/3611852/45022176-d9481280-b033-11e8-8792-cf15961fcfbf.png)

### Console errors
Spongeforge detect a leak on baltop 
https://gist.github.com/xion87/ca15727bfb1c61bc198a2153d8605f02

### Related Configuration Files
https://gist.github.com/xion87/02115f77713f6488a4b588b6919c0556

**Comment by MarkL4YG** [comment]
I would say if this does not directly affect performance in a dramatic way, it is safe to say this may be implicitly fixed by the sql-refactor that is in the works.
