### ISSUE TITLE
Job related permissions have no effect

### ISSUE THREAD

**Issue by ExplodingONC** [Erigitic/TotalEconomy#305]
Sponge Version:  7.1.0-BETA-3361
Forge Version:  14.23.4.2705
Total Economy Version:  1.8.1

### Description of issue
permissions like "totaleconomy.command.job.toggle" or "totaleconomy.command.job.set" have no effect, and I can't use /job toggle or /job set with these permissions. The only way to use these two commands is to give the permission "totaleconomy.command.job", but this means that everyone can set a job to other people, as "totaleconomy.command.job.setother" is also included.
I'm using Luckperm to manage the permissions, is this a bug or compatibility issue?
### Console errors
none
### Steps to reproduce
none
### Related Configuration Files
none

**Comment by MarkL4YG** [comment]
That's an issue with the implicit wildcards. I've opened an issue about that some time ago.
You can disable the implicit wildcard in LuckPerms configuration file and resort to bukkit-style ``*`` until the permission is changed in TE.

**Comment by MarkL4YG** [comment]
@ExplodingONC did that resolve your issue or does it still persist?

**Comment by Erigitic** [comment]
Closed in favor of https://github.com/Erigitic/TotalEconomy/issues/205. Continue discussion there.
