### ISSUE TITLE
No Money or Exp for breaking Crops [1.8.1], but in 1.7.1 Api7 it did.

### ISSUE THREAD

**Issue by Play4K** [Erigitic/TotalEconomy#306]
Sponge Version:  1.12.2-2705-7.1.0-BETA-3361
Forge Version:  1.12.2 - 14.23.5.2768
Total Economy Version:  1.8.1

For breaking crops you dont get any money or exp...
I tried different configurations to fix it. But i cant fix it however.
I tried to group all jobs into one job as "worker".
Then i got exp and money for breaking crops but didnt got money or exp for killing mobs.
If this issue would be fix as soon as possible. It would be very nice of you.
But in 1.7.1 Api7, breaking Crops worked.

NO CONSOLE ERRORS.

**Comment by Play4K** [comment]
Someone already submit this issue. It was post "#282 farmer bug?". But he got now answer or any fix possibles. And i myself found any fixes too, after trying a lot.

**Comment by MarkL4YG** [comment]
Please attach your config files and the server log using a gist.
I will take a look at them later today or tomorrow depending on when I have the time.

**Comment by Play4K** [comment]
https://gist.github.com/Play4K/ca8cb7e86ae725acccb518c08645203e

**Comment by Play4K** [comment]
Even reinstalling it and letting it by default, doesnt do anything... Just so you know it..
I tried to start the server without any mods, only with the Total economy plugin. It didnt fix it.

**Comment by MarkL4YG** [comment]
I didn't find anything immediately catching my eye so I will try to reproduce this issue during the next days.

**Comment by MarkL4YG** [comment]
Not exactly "the next days" and I'm sorry for keeping you waiting.  
But I have found the culprit.  
  
The [default configuration](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/resources/assets/totaleconomy/jobsets.conf#L6) does not match the [source code](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/jobs/TEAction.java#L53) of the plugin.  
While the configuration uses ``growthTrait``, the plugin looks for ``growth-trait``.  
This is a bug and I will talk to Eric about what of both we want to use.  
  
For your part exchanging all occurrences of ``growthTrait`` with ``"growth-trait"`` in the job sets file should resolve your issue.

**Comment by MarkL4YG** [comment]
You could also wait for this PR to get approved and a hotfix to be released in order to have the issue fixed without having to change the sets file.
