### ISSUE TITLE
Not able to turn off messages.

### ISSUE THREAD

**Issue by 2iguys** [Erigitic/TotalEconomy#313]
Sponge Version:  7.1.0-70763aa8
Forge Version:  14.23.5.2768
Total Economy Version:  1.8.1

### Description of issue
Unable to fully disable job task msg's /job toggle only disables it till next login. and changing it in the config doesn't keep it disabled.

### Console errors
none shown.

### Steps to reproduce
toggle notifications off and rejoin the server, then preform your job task. the message will show in chat again

THE MAIN issue I have with this is that it steals the chat. it would be fine if it didn't notify for every item and consolidated them after you complete the task and wait like 10 seconds.

**Comment by MarkL4YG** [comment]
Interesting approach imo.  
I'll think about that at home later.

**Comment by MarkL4YG** [comment]
I took a look into the code around the job notifications and it seems like the reset you're mentioning should not be happening.  
Can you provide your full server log and your accounts config, aswell as the UUIDs of players experiencing this issue, please?

**Comment by 2iguys** [comment]
[troubleshoot.zip](https://github.com/Erigitic/TotalEconomy/files/2568627/troubleshoot.zip)
heres anything pertaining to notifications and jobs, it affects me as the server owner, not sure if I somehow am bypassing the config personally, cause I asked my admin and he said that nothing popped up for him... not sure though.

**Comment by 2iguys** [comment]
ok, after testing this morning it seems to have potentially resolved itself. however I wonder about the idea of delaying the chat notifications or having an option for that. that way it tells you the total you've earned once you complete your job.
if I get the issue again I will post once more, but it isn't affecting my server anymore.

**Comment by MarkL4YG** [comment]
I'll probably create a separate issue for the notification batch feature as I think it is potentially interesting.

**Comment by MarkL4YG** [comment]
Glad to hear your issue is resolved.  
Feel free to re-open, should the issue re-appear.
