### ISSUE TITLE
Console error Could not pass DestructEntityEvent$Death$Impl

### ISSUE THREAD

**Issue by infamyreloaded** [Erigitic/TotalEconomy#322]
Minecraft: 1.12.2
SpongeAPI: 7.1.0-70763aa8
Sponge: 1.12.2-7.1.4
SpongeForge: 1.12.2-2768-7.1.4
Minecraft Forge: 14.23.5.2768
Total Economy Version: 1.8.1

### Description of issue
Totaleconomy gives me an error in console. I'm not sure when it happens but it looks like when a player kills a mob. I have jobs disabled also in case that matters.
### Console errors
https://hastebin.com/kesomuziba.rb

**Comment by MarkL4YG** [comment]
Hey there,
thank you for submitting this issue.  
According to the information from the logs, the ``EntityDamageSource`` seems not to contain the actual source representation (which should be the player in this case) throwing an exception [in this line](https://github.com/Erigitic/TotalEconomy/blob/5a67f9eb4a5a0c7c8e5cfa2615c17294810bbf27/src/main/java/com/erigitic/jobs/JobManager.java#L890).  
We can work-around by including an additional null-check in the code. However, that value being ``null`` conflicts with the interface contract as it is not an ``Optional`` value. There might be something going wrong deeper in Sponge if you ask me.  
  
Can you provide more information on your ingame setup?  
* What weapon are you using to kill the mob?
* What mob are you trying to kill?
* Do you have mods installed? If yes, please name them.  

---
@Erigitic what do you think?

**Comment by infamyreloaded** [comment]
I'm not sure what weapon it is, but I'll keep an eye out. I'll check this weekend and see if I can find what item and mob causes it. It probably has something to do with techguns because that mod has so many error.

**Comment by infamyreloaded** [comment]
Just giving an update, haven't forgot about it. Still trying to find the cause.

**Comment by infamyreloaded** [comment]
So I did 2 things and haven't seen the error since then. I'm not sure which was the cause, but I updated my forge version and updated my techguns version and I haven't seen the error pop up again. I'm thinking it was one of the the guns in techguns but not sure. If I ever see it again I'll try to find it and post it here but you can close this for now.

**Comment by MarkL4YG** [comment]
Alright, let's hope there's not going to be a reason for you to get back to this ;)  
It is possible that the Forge and/or Techguns update fixed a bug that was causing this issue imo.

**Comment by infamyreloaded** [comment]
That's most likely the case. There were some other problems I was having before updating and those are gone now.
