### ISSUE TITLE
I'm not sure how to aquire the new version.

### ISSUE THREAD

**Issue by BelowAverageBen** [Erigitic/TotalEconomy#325]
I'm experiencing the issue that was fixed with the 1.8.2 update (receiving 0 payout rewards) but the latest version I can find is 1.8.1. I tried to build the java from the source and got lost very quickly and spent far too much time watching tutorials to get it to work. If anyone could help me out that would be great.

**Comment by MarkL4YG** [comment]
1.8.2 is not released yet.  
You could wait for @Erigitic to release that version or build it yourself.  
Building it yourself is fairly easy:
* Have Java 8 JDK installed
* Clone the repository (or use the ZIP download and extract the archive)
* Open a command prompt in that folder
* ``gradlew.bat build``  
  
After that command returns ``BUILD SUCCESSFUL``, you can find the plugin jar in ``build/libs``

**Comment by BelowAverageBen** [comment]
Where is build/libs? I built it successfully but can't seem to find it. Thanks for the quick response.

**Comment by BelowAverageBen** [comment]
I got it set up. Thanks for the quick and helpful response.

**Comment by MarkL4YG** [comment]
Always glad to help :)
