### ISSUE TITLE
Jobs set for More Creatures Mod?

### ISSUE THREAD

**Issue by AkiSenpai96** [Erigitic/TotalEconomy#326]
Is there a way to use the Total Economy to make Warrior Job kill More Creatures mobs? Like getting the exp and the money?

**Comment by MarkL4YG** [comment]
Yes, you can add the entity names to a job set just as vanilla entities.  
See the examples that are generated on the first start of the plugin.

**Comment by Erigitic** [comment]
It's been a while since this issue has had any activity so I'm going to close it. If you're still having issues with this, please feel free to reopen. Thanks.
