### ISSUE TITLE
An error occurred while creating a new account!

### ISSUE THREAD

**Issue by NightSommelier** [Erigitic/TotalEconomy#329]
Sponge Version:  1.12.2-7.1.5
Forge Version:  14.23.5.2768
Total Economy Version:  1.8.1

### Description of issue
An error occurred while creating a new account! Always shows this error when putting blocks in lava.

### Console errors
[21:25:47] [pool-3-thread-18/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:25:47] [pool-3-thread-19/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:25:47] [pool-3-thread-16/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:25:48] [pool-3-thread-16/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:25:55] [pool-3-thread-19/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:26:02] [pool-3-thread-16/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:26:05] [pool-3-thread-16/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:26:35] [pool-3-thread-15/WARN] [totaleconomy]: An error occurred while creating a new account!
[21:26:37] [pool-3-thread-15/WARN] [totaleconomy]: An error occurred while creating a new account!

### Steps to reproduce
Always shows this error when putting blocks in lava.

Is this problem possible due to the plugin JobsLite?
https://ore.spongepowered.org/Flibio/JobsLite

**Comment by MarkL4YG** [comment]
Hey there,

can you please attach a gist with your server log files and your totaleconomy configuration so we can investigate the cause?  
Remember to strip the database password from the main configuration in case you've got SQL enabled.

**Comment by NightSommelier** [comment]
[configs.zip](https://github.com/Erigitic/TotalEconomy/files/2847198/configs.zip)
[logs.zip](https://github.com/Erigitic/TotalEconomy/files/2847199/logs.zip)

**Comment by MarkL4YG** [comment]
Okay, I took a look quickly.  
Looks like you don't have database support enabled which means that TotalEconomy is storing the account information on the disk.  
A look at [the code](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/config/AccountManager.java#L230) tells me that there's an IOException being raised.  
Possibly something with the filesystem access failes.  

I'll create a PR which will finally add the exception to the log message so we can see what error is occurring.

**Comment by MarkL4YG** [comment]
If you happen to know how to build the plugin from source, feel free to test a build from that branch and provide the exception that's being logged.

**Comment by NightSommelier** [comment]
[2019-02-09-1.log](https://github.com/Erigitic/TotalEconomy/files/2847365/2019-02-09-1.log)
[totaleconomy.zip](https://github.com/Erigitic/TotalEconomy/files/2847367/totaleconomy.zip)
I tried to use MySQL

**Comment by MarkL4YG** [comment]
If that didn't change a thing, we really need you to use the build where the exception is included in the log message as that will tell us what error has occurred.  
I would recommend you to build the jar from the source branch in the pull request but (in case you don't want to or don't know how to do that) [here's a pre-built jar file](https://drive.google.com/open?id=1rZtOn9DbrwdvxO-rHUWuqpuyOfiOzw0y) which you can try __in a non-production__ environment.

**Comment by NightSommelier** [comment]
I found what the problem is! Error in writing accounts.conf file.
It records one or more entries with an error — a problem in recording the user ID (without quotes).

```
"34e76d91-cefe-3f1d-a2b5-6b114e59f0a8" {
    hryvnia-balance=782
    job=unemployed
    jobnotifications=false
}
"8d57ee54-e30f-3c3e-ae79-6cd21beaf117" {
    hryvnia-balance=200
    job=unemployed
    jobnotifications=false
}
"8d84e2e6-5adf-36b4-b7d5-a560b03d26e4" {
    hryvnia-balance=938.69
    job=unemployed
    jobnotifications=false
}
b1e628cc-5f71-308d-b853-563cfcd8073a {
    hryvnia-balance=377
    job=unemployed
    jobnotifications=false
}
version=1
```

**Comment by NightSommelier** [comment]
I found what the problem is! Error in writing accounts.conf file.
It records one or more entries with an error — a problem in recording the user ID (without quotes).

```
"34e76d91-cefe-3f1d-a2b5-6b114e59f0a8" {
    hryvnia-balance=782
    job=unemployed
    jobnotifications=false
}
"8d57ee54-e30f-3c3e-ae79-6cd21beaf117" {
    hryvnia-balance=200
    job=unemployed
    jobnotifications=false
}
"8d84e2e6-5adf-36b4-b7d5-a560b03d26e4" {
    hryvnia-balance=938.69
    job=unemployed
    jobnotifications=false
}
b1e628cc-5f71-308d-b853-563cfcd8073a {
    hryvnia-balance=377
    job=unemployed
    jobnotifications=false
}
version=1
```

**Comment by MarkL4YG** [comment]
Sanitation and formatting is done by Configurate, not Totaleconomy.
In addition, a formatting error is generally unlikely to cause issues when saving the configuration as deserializers generally don't know or care about what the result looked like in the end.

**Comment by MarkL4YG** [comment]
Can you please provide the error log generated by the fixed build?  
This way, the ``IOException`` will be logged and we can clearly see what the culprit is.

**Comment by NightSommelier** [comment]
[latest.log](https://github.com/Erigitic/TotalEconomy/files/2856852/latest.log)

**Comment by MarkL4YG** [comment]
Thanks for sending your log. However, you are not using the build which includes the exception in the log.  
@Erigitic can you please merge the PR, so we can get him an official download for this.

**Comment by Erigitic** [comment]
Merged.

**Comment by MarkL4YG** [comment]
@Erigitic Thanks :)

@NightSommelier Now you can build the branch ``develop`` to get a snapshot of TotalEconomy 1.8.2 and try that version on your server.  
See #325 for details on that.

**Comment by NightSommelier** [comment]
Thank you, I will try, I will write about the results later.

**Comment by NightSommelier** [comment]
[debug.log](https://github.com/Erigitic/TotalEconomy/files/2858651/debug.log)
[latest.log](https://github.com/Erigitic/TotalEconomy/files/2858652/latest.log)

**Comment by MarkL4YG** [comment]
> java.nio.file.AccessDeniedException: D:\MinecraftServer\.\config\totaleconomy\485333533435188accounts.conf.tmp -> D:\MinecraftServer\.\config\totaleconomy\accounts.conf  

There you have it: It's a file permission issue.  
The server appears to be unable to write to the configuration file.  
Please check the filesystem permissions and make sure the user running the server is allowed to write to the configuration directory.

**Comment by NightSommelier** [comment]
The file has permission and does not use anything except the server.

**Comment by MarkL4YG** [comment]
Are you running the server on a linux system?
If so, can you please show us the output of ``ls -la`` from within the totaleconomy configuration folder?

**Comment by NightSommelier** [comment]
No, on Windows 10 Pro x64

**Comment by MarkL4YG** [comment]
Oh, my bad. Could've told that from your logs 😅 .  
  
I've tried reproducing your issue using:  
* Java ``1.8.0u102``
* Forge ``14.23.5.2768``
* SpongeForge ``1.12.2-2768-7.1.5``
* And the latest TotalEconomy ``1.8.2`` snapshot
However, I was not able to reproduce your issue, even with the server also being located on a secondary drive (``D:\MinecraftServer``).  
I am quite sure that something with your directory permissions is off as I can not imagine any other reason an ``AccessDeniedException`` would be thrown.  
Can you elaborate on your server setup? Do you use multiple Windows users, are you running on a Windows Server or is it your local machine? Do other users on that machine have access to the server? Does this issue persist when you copy the whole server folder into a new location and run the server from there?

**Comment by NightSommelier** [comment]
I started the server on Linux Server, everything works fine. Apparently the problem with Windows 10.
