### ISSUE TITLE
Increase reward by rank up ?

### ISSUE THREAD

**Issue by TonyoBlaster** [Erigitic/TotalEconomy#338]
Hi!

How can I change the configuration files to increase the rewards at each rank up? To force players to farm.

*At the same time, players can't be rewarded when they took their wheat, cause there is the anti-cheat, how to solve that ?

**Comment by MarkL4YG** [comment]
You could just create another job with slightly altered sets to increase the rewards.

**Comment by TonyoBlaster** [comment]
Wut ? I mean, I want to increase by levels, not change the job bro

Cause now, u can rank up wow cool, but what do u have ? U see ?

**Comment by MarkL4YG** [comment]
You could create "ladders" this way. With "elite-miner" requiring one to be at least a level 10 "experienced-miner" for example.  
If you do not want that and would love the project to move on faster than our free time allows, feel free to submit changes using a PR :)

**Comment by TonyoBlaster** [comment]
Okay... why not? But there will be severals jobs when players will /job... 

By the way, I can't rename jobs ? I mean, miner to Miner and after a restart of the server (not just /job reload) if I click on Miner the command says "job miner doesn't exist" ? Why ?

**Comment by MarkL4YG** [comment]
that's because we lowercase letters in the code. With the current implementation, user sanitized job names are not possible.  
That's why we will change to ``UUID``s for jobs which will make names freely modifiable.
