### ISSUE TITLE
Can't add jobsets

### ISSUE THREAD

**Issue by Peacefuldwarf** [Erigitic/TotalEconomy#342]
Sponge Version:  Spongeforge-1.12.2-2768-7.1.5
Forge Version:  forge-1.12.2-14.23.5.2768
Total Economy Version:  1.8.1

### Description of issue
Jobs and jobsets works perfectly upon fresh install but whenever I edit the "jobsets.conf" and add a few extra sets for my new jobs it fails to load the config upon restart and causes the miner class to not work anymore.
### Console errors
"An error occurred while creating/loading the jobSets configuration file!"

"19.05 21:03:32 [Server] Server thread/WARN [totaleconomy]: Job miner has the nonexistent set "ores" 19.05 21:03:33 [Server] Server thread/WARN [totaleconomy]: Job miner has the nonexistent set "ores""

### Steps to reproduce

Edit "jobsets.conf" 

### Related Configuration Files

https://gist.github.com/Peacefuldwarf/a1898d08c9cd32b68be9906f38278644

I've edited the part right under miner as seen

Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Your configuration file is not valid HOCON, please make sure that it is valid and re-try reproducing the issue.
Would recommend using [HoconLint](http://www.hoconlint.com/) for that.
