### ISSUE TITLE
Migration to MySQL Database ?

### ISSUE THREAD

**Issue by TonyoBlaster** [Erigitic/TotalEconomy#343]
Is there a way to migrate accounts to MySQL Database ? I mean, I created one and no problem here, but how can I migrate my old data to the database now ?

Thank's in advance !

**Comment by MarkL4YG** [comment]
Hi,

I once wrote a tiny plugin to do that. You can find the source code [here](https://github.com/MarkL4YG/TE-SqlHelper)

Open an issue there if you run into any issues as I am not quite sure how up to date the plugin is :innocent:
