### ISSUE TITLE
TE Job signs not functioning.

### ISSUE THREAD

**Issue by SeaDonkey81** [Erigitic/TotalEconomy#344]
Sponge Version:  1.12.2-2768-7.1.5
Forge Version:  14.23.5.2814
Total Economy Version:  1.8.1

### Description of issue
Signs are not working for me.
I followed the instructions: 
First line: [TEJobs]. Second line: Job name.
 The sign does not change colors and nothing happens when I click the sign to accept the job.

### Console errors
None

**Comment by MarkL4YG** [comment]
Hey there,  
please attach your server log files and your job configuration files (jobSets.conf & jobs.conf) using a gist so we can have a look on what exactly may be malfunctioning.  
If the sign does not change its colors, there's definitely something wrong while the sign is created. Therefore, clicking will not work either.

**Comment by SeaDonkey81** [comment]
> Hey there,
> please attach your server log files and your job configuration files (jobSets.conf & jobs.conf) using a gist so we can have a look on what exactly may be malfunctioning.
> If the sign does not change its colors, there's definitely something wrong while the sign is created. Therefore, clicking will not work either.

added gist link

**Comment by MarkL4YG** [comment]
Your log contains sensitive data!  
Please delete the gist, reset your database password and then re-do the gist without the data!  
If you used the same credentials for TotalEconomy, the plugin is likely not working because it was not able to initialize the database.

**Comment by MarkL4YG** [comment]
I see you did :) :+1:   
Now, please make sure your database settings are correct. There are multiple plugins failing to connect to the database server. This includes TotalEconomy.  
Your connection url should look something like this: ``jdbc:mariadb://your-host.com:3306/your-database?username=your-user&password=your-password``.  
For TotalEconomy, the username & password settings are separate config options so the part from the ``?`` should be omitted.  
  
Please try that and tell us if your issue has been fixed. If you require more assistance, feel free to ask :slightly_smiling_face:

**Comment by SeaDonkey81** [comment]
Thank you.. Taking out the http in the url fixed it.

**Comment by MarkL4YG** [comment]
Glad to have helped 😉  
If your issue is resolved now, please close the issue so it is no longer tracked active :)
