### ISSUE TITLE
None existent sets

### ISSUE THREAD

**Issue by SeaDonkey81** [Erigitic/TotalEconomy#345]
Sponge Version: 1.12.2-2768-7.1.5
Forge Version: 14.23.5.2814
Total Economy Version: 1.8.1

### Description of issue
Lumberjacking and Mining don't drop any exp orbs.

### Console errors
Server thread/WARN [totaleconomy]: Job lumberjack has the nonexistent set "lumberjackSet"

Server thread/WARN [totaleconomy]: Job miner has the nonexistent set "ores"

### Related Configuration Files
https://gist.github.com/SeaDonkey81/23ac2c6b09ffebcc9537011e35953f99

**Comment by MarkL4YG** [comment]
Hey there,  
the casing in your configuration files is off (``lumberjackset`` != ``lumberjackSet``) and additionally, your jobSet configuration is not syntactically correct (according to [HOCONLint](http://www.hoconlint.com/) you are missing a closing ``}`` at the end).

**Comment by SeaDonkey81** [comment]
Thanks, that fixed it.

 My next issue:  Even though the blocks are dropping exp orbs I am not gaining any exp in that job field.

**Comment by MarkL4YG** [comment]
Good 👍 

Even though one might think that, exp orbs are not related to TEs job exp counter. TE only adds the amount of exp specified in the job set for that specific block.  
Can you tell us:
* Which block you are breaking (ID, mod or vanilla, variant)?
* Was this block naturally generated?

**Comment by SeaDonkey81** [comment]
minecraft coal and yes, it was naturally generated. I mined 13 blocks of coal and my job command still stated level 1 - exp 0/100

**Comment by MarkL4YG** [comment]
And your job is actually "miner"? :thinking:

**Comment by SeaDonkey81** [comment]
Correct

**Comment by SeaDonkey81** [comment]
It's fixed. It must have been something conflicting with griefprevention. I had to uninstall it because i was getting some errors. I just now reinstalled GP and i'm getting exp from jobs now.

**Comment by MarkL4YG** [comment]
That might well be :eyes:  
Glad to hear that it's fixed now :slightly_smiling_face:
