### ISSUE TITLE
Players being able to edit job signs.

### ISSUE THREAD

**Issue by SeaDonkey81** [Erigitic/TotalEconomy#350]
Sponge Version: 1.12.2-2768-7.1.5
Forge Version: 14.23.5.2814
Total Economy Version: 1.8.1

### Description of issue
When players on my server join a job they are also able to edit the sign.

### Console errors
None

### Steps to reproduce
Create a job sign, have another player join that job.

**Comment by MarkL4YG** [comment]
Hi,

that's probably an event that we need to cancel..

**Comment by SeaDonkey81** [comment]
Would that be something i could change? I noticed that if i hold shift + right click the job is accepted and the edit sign does not pop up.

**Comment by MarkL4YG** [comment]
Nah, that's probably an interaction event that we will need to cancel so the actual editing of the sign doesn't start in the first place.  
By shift+right-clicking you are doing somewhat the same thing but on the client side.  
  
However, this should only be considered a minor issue as signs do not allow players to bypass the restrictions to join the job. Additionally, protection from editing can be achieved by using any protection plugin that supports a distinction between interaction and editing.

**Comment by SeaDonkey81** [comment]
The protection plugin I'm using doesn't give support for edit protection. Unfortunately it's the only protection plug that doesn't conflict with my other mods. Thanks.
