### ISSUE TITLE
TotalEconomy doesn't work with PHP7

### ISSUE THREAD

**Issue by ghost** [Erigitic/TotalEconomy#351]
Latest Sponge version, latest TotalEconomy version, as always. So, with a MySQL server under PHP 7 no problem, but with PHP 5 the plugin cannot connect to the database...

Here is the informations about the PHP 5 Server :

Apache / 2.4.25 (Debian)
Database client version: libmysql - 5.5.60
PHP extension: mysqliDocumentation mbstringDocumentation
PHP Version: 5.6.37-0 + deb8u1

**Comment by MarkL4YG** [comment]
Hi there,  
TotalEconomy neither runs on nor has anything to do with your PHP-Version so there definitely something else wrong. Do the MySQL versions differ and can you please provide some logs from the working and non-working setup?

**Comment by TonyoBlaster** [comment]
The one who works :

**Apache / 2.4.25 (Debian)
Client Database Version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $ Id: b5c5906d452ec590732a93b051f3827e02749b83 $
PHP extension: mysqliDocumentation mbstringDocumentation
PHP Version: 7.0.33-0 + deb9u1**

The one who doesn't works:

**Apache / 2.4.25 (Debian)
Database client version: libmysql - 5.5.60
PHP extension: mysqliDocumentation mbstringDocumentation
PHP Version: 5.6.37-0 + deb8u1**

The database server is the same, and for example if I run "/baltop" : 

_java.lang.NullPointerException: null at com.erigitic.commands.AdminPayCommand.execute(AdminPayCommand.java:74) ~[AdminPayCommand.class:?] at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5-RC3511] at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5-RC3511] at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5-RC3511]_

**Comment by TonyoBlaster** [comment]
In local (no mysql connection), the plugins works like a charm... I just don't know what's happening

**Comment by MarkL4YG** [comment]
``NullPointerException``s in TotalEconomy's SQL code are usually caused by an initialization error. Can you add your log file into a [gist](gist.github.com) so I can take a look at that error too?  
_Note: The SQL initialization logs may contain your database credentials!_ __Please remove them before posting your logs__  
  
Sponge already brings mariadb/mysql connectors and uses them via. ``HikariCP`` so there's is no need for any mysql plugin to be additionally installed.

**Comment by TonyoBlaster** [comment]
Into a gist ? I don't understand what I'm supposed to do ^^' ?

Do u want the .conf file ? The logs when TotalEconomy starts ?

**Comment by TonyoBlaster** [comment]
I think the problem is from the MySQL Server, cause without SQL no problem, and I tried in the config with the hostname, the IP, with the brackets or not ( [ ] ), with the :3306 or not ... and nothing works.

**Comment by MarkL4YG** [comment]
> Do u want the .conf file ? The logs when TotalEconomy starts ?

I would like to see your ``latest.log`` to take a look at the start-up log messages from when the DB connection appears to be broken.  
If you add your configuration too, I can additionally check for any errors in there but also remember to replace your credentials first.

**Comment by TonyoBlaster** [comment]
Here u are : https://gist.github.com/TonyoBlaster/5e0be0009a87dfc125834f0d081f66af

**Comment by MarkL4YG** [comment]
This does not seem right to me and I am not quite sure what to make of that. I'll need to think about that and look up some stuff about the Sponge-MySQL connection. In the mean time, can you elaborate on what exactly you are changing in your server so that this error occurs?

**Comment by TonyoBlaster** [comment]
I just upload my old server on my new server (new hosting provider u know) and here we are. On the ancient, no problem, but on the new, it's seems that there is a problem with their MySQL server.

As I said :

The one who works :

**Apache / 2.4.25 (Debian)
Client Database Version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $ Id: b5c5906d452ec590732a93b051f3827e02749b83 $
PHP extension: mysqliDocumentation mbstringDocumentation
PHP Version: 7.0.33-0 + deb9u1**

The one who doesn't works:

**Apache / 2.4.25 (Debian)
Database client version: libmysql - 5.5.60
PHP extension: mysqliDocumentation mbstringDocumentation
PHP Version: 5.6.37-0 + deb8u1**

**Comment by TonyoBlaster** [comment]
These are the informations displayed on the PHPMyAdmin menu.

**Comment by MarkL4YG** [comment]
Might well be, but the PHP version and extension does not have an influence on anything running on your Minecraft server. The server is running on Java and has its own set of libraries. If you've changed your hosting provider, I would guess that there's something wrong with the new MySQL credentials in your configuration. Did you verify that or can you provide your configuration _with your account credentials replaced_?

**Comment by TonyoBlaster** [comment]
Np, I finally have the cause... the plugin fails to load the JNA libs because of their "security settings".

Thank's for ur time

**Comment by MarkL4YG** [comment]
Ah, that explains why :sweat_smile: .
However, the libraries are loaded from Sponges side and should have the same issue for all plugins that do not manage SQL themselves like LuckPerms does for historic reasons.  
  
You're welcome
