### ISSUE TITLE
Error occurred when executing command

### ISSUE THREAD

**Issue by MrBringBacon** [Erigitic/TotalEconomy#352]
Was just wondering if maybe this is a common issue and someone may just have a quick fix.
The Jobs were working earlier today, and I'm not actually sure what I did to make it happen, but now I get this when I type /job

Just the Error in Console; https://pastebin.com/n8xPzCHR
Full Log; https://gist.github.com/MrBringBacon/c6a178478f818ff1ff720ee051d0741b

Thanks in advance!

**Comment by MarkL4YG** [comment]
Hi there,
there's a much earlier error in your log showing that the initialization of TE already failed. It is fairly normal for commands not to work either afterwards.  
What version of Sponge and TotalEconomy are you using?

**Comment by MrBringBacon** [comment]
Sponge Version: 1.12.2-2825-7.1.6
Forge Version: 1.12.2 - 14.23.5.2838
Total Economy Version: 1.8.1

**Comment by MrBringBacon** [comment]
It's not just /job, it's /shop buy  as well

**Comment by MarkL4YG** [comment]
May I also see your configuration files, please? (Remember to replace your SQL login credentials)

**Comment by MrBringBacon** [comment]
I don't believe I have a SQL login. 
and which config would you like? Just the totaleconomy.conf?

**Comment by MrBringBacon** [comment]
hmmm... It may have been that I put a jobset under the job config instead of the jobset config..
I just deleted all the configs and reinstalled them, and it seems to be working fine now.

I have two other question, I believe they're more simple than the previous lol. 

**1) How do I set custom mobs and blocks for the jobs?**

Is it like this? 
 kill {
            aoa3:sasquatch{
                exp="10"
                money="5.00"
            }

    ores {
        break {
            "aoa3:limonite_ore" {
                exp="15"
                money="3.75"
            }

Or do I need the Block, and Mob ID number?

**2) Is there a way to increase the salary per level of job?**

**Comment by MrBringBacon** [comment]
I've tested the mob one as typed above, and it doesn't seem to be working.
I can do /spawnmob aoa3:sasquatch and it'll work.

**Comment by MarkL4YG** [comment]
> 2) Is there a way to increase the salary per level of job?

Not at the moment but there's an issue about some sort of scaling for the rewards per level. At the moment, you can only allow something like this by creating another job with higher-rewarding jobsets that requires a certain level in the normal job. Something like "hunter" and "master-hunter" as two jobs where you need to be "hunter level 55" in order to switch to the "master-hunter" job which would then have better rewards.  
  
> I've tested the mob one as typed above, and it doesn't seem to be working.  
  
Custom mob id entries in the job sets should be supported just as vanilla ones. Could you attach your job sets configuration please?

> Or do I need the Block, and Mob ID number? 

TE is using string block and entity IDs and not the numerical representation.

**Comment by MrBringBacon** [comment]
https://pastebin.com/iQARdZFs

Am I possibly in the wrong job? I see mobs, but it does't say "warriorset" or anything.
The only one I see is "Lumberjackset"

**Comment by MrBringBacon** [comment]
I then tried killing a skeleton, and it didn't give me anything anymore.
Maybe I messed up the code somehow?

This is what it says in console;
[07:53:54] [Server thread/WARN] [totaleconomy]: Job warrior has the nonexistent set "mobs"

In the jobs config, it does have the set "mobs" so idk..

**Comment by MarkL4YG** [comment]
There is at least one trailing ``}`` missing in your sets configuration, which means its content will not be read correctly. There should've been a message in your server log about that too.
