### ISSUE TITLE
Incompatible with RLCraft 2.7

### ISSUE THREAD

**Issue by LemADEC** [Erigitic/TotalEconomy#355]
Sponge Version:  1.12.2-2838-7.1.7-RC3924
Forge Version:  14.23.5.2838
Total Economy Version:  1.8.1

### Description of issue
When used with the RLCraft modpack, breaking stone and wood log will get you no drops.
Issue was observed while jobs and database are disabled.

### Console errors
No logs in console when breaking logs or stone.

### Steps to reproduce
1- Boot an RLCraft server
2- Level up your harvesting and mining skills to 4
3- Use flint axe on a tree to get logs
or use a flint pick on stone to get rock
=> no logs nor rocks are dropped

### Related Configuration Files
https://gist.github.com/LemADEC/a6c7a588a3bdcf84f6dfa998fbce76ca

**Comment by MarkL4YG** [comment]
Hi,
please attach more information about your server setup. What other mods are installed? Do you use other plugins as well? Does this issue persist when no other mods and plugins are installed?
I would also like to ask you to attach your server log files so we can take a look at whether or not there's something reported in there that may be the cause or a related symptom.

**Comment by LemADEC** [comment]
That's an intermittent issue, unrelated to TotalEconomy.
