### ISSUE TITLE
SQL Support

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#36]
Things that need to be tested before launching:

- [x] Job notification toggle
- [x] Account creation
- [x] Has account check returns properly
- [x] Job exp updates properly
- [x] Job levels update properly
- [x] Job exp is retrieved properly
- [x] Job levels are retrieved properly

**Comment by At-M** [comment]
I'd like to see this too :+1: 
External SQL would be cool

**Comment by MarkL4YG** [comment]
Remember when it comes to larger user counts (per server) an SQL database may not be the best option since you can't really bundle transactions.
Otherwise SQL support will be an easy way to access data from another application.

**Comment by Erigitic** [comment]
Oh wow this is an old one. Let me go ahead and set a milestone on this one so we can get it added to the next release.

**Comment by mister-man** [comment]
Hello together, hello @Erigitic

why you removed the feature from 1.5.1? It's my personal favorite feature. I need it for homepage integration (php) and for economy sharing between servers (bungeecord).

Thanks

**Comment by MarkL4YG** [comment]
@mister-man probably because he's busy resolving some other issues before implementing completely new features.

**Comment by mister-man** [comment]
@MarkL4YG  Yes I tested it. But it's pre. So it was possible that the feature is disabled or else. Or a reason could, that there are problems with the api design and api is incompatible with a multi server environment.

But now I know the reason, thanks :)

**Comment by Erigitic** [comment]
Adding SQL support is going to take longer then I expected which is why I removed the milestone. As well as that, I am focusing on bug fixes for v1.5.1 as there seems to be quite a few that snuck their way into v1.5.0. 

SQL support will be added sooner or later, but not until I have a large amount of time on my hand as there is a lot of code that would need to be altered.

**Comment by MarkL4YG** [comment]
Afaik the ``JobManager`` still lacks SQL support and for some reason the ``AccountManager`` initializes the ``level`` and ``exp`` tables while the ``JobManager`` manages them in file mode.
Although money and transactions are more important I'd say that it should be decided whether or not jobs will also have SQL support and if applicable this issue reopened.
