### ISSUE TITLE
no Kill reward when using non-vanilla weapons

### ISSUE THREAD

**Issue by Tocirah** [Erigitic/TotalEconomy#362]
Sponge Version:  spongeforge-1.12.2-2838-7.1.10-RC3994
Forge Version:  forge-1.12.2-14.23.5.2847
Total Economy Version:  TotalEconomy-1.8.1

When killing mobs with non-vanilla weapons, for example _ModernWarfare_ Guns, the player does not get the reward for actually Killing the mob. My first guess was that using this mod keeps the player from getting the kill and actually have the weapon/entity get the kill. But after a bit more testing I did receive achievements regarding combat from other mods and vanilla, making me think that the player still Kills.
After some research i found your guys' fix on how a bow kill is handled to where the entity, or damageSoucre, gets linked to the creator. Meaning that it should already be fixed. Do you think that this mod in particular has it so the way the mob is killed is not linked back or able to be linked back to the player?
Would you have some suggestions in things i can try to get this to work, using either your configs or code by way of checking death cause? Or would this be a problem regarding mods used?
Thanks in advance.

I currently don't have custom configs.

**Comment by newresource-dev** [comment]
I checked the weapons from the ic2ex mod, the plugin works correctly. Rewards for killing mobs are available.
**_Checked on a mining laser and nano saber._**
maybe your problem is directly related to your weapon mod?

**Comment by Tocirah** [comment]
Yea, after some more testing and looking at code from the mod in question, it seems that the mod uses really weird death cause, making it a 3 step progress as far as i can see. mob gets killed by entity(bullet), that gets linked to who shot it, who would normally be a player, but in this mod its the gun, that is operated by the player. So i think the death cause is set to the gun and does not get linked to the player when using your system. So there is basically nothing wrong on your guys' end, this mod is just kinda weird ;3.
Thanks tho, for checking it with other mods, did narrow it down.

**Comment by MarkL4YG** [comment]
Glad you found the cause of this! :slightly_smiling_face:
