### ISSUE TITLE
SQL Database Connection Issues

### ISSUE THREAD

**Issue by itzrobotix** [Erigitic/TotalEconomy#380]
Sponge Version: 1.12.2 7.3.0
Forge Version:  14.23.5.2854
Total Economy Version:  1.8.1

I'm trying to connect TE to mysql database but it won't connect, keeps saying check the database credentials but I'm 100% sure they are correct and I've tried every possible version of the "url" option to no avail, I just want to know what I'm doing wrong because I can't see it. No errors about syntax or anything, just that the credentials aren't correct. I think my issue is with the "url" option but I'm not sure.

Here is a screenshot of the database details excluding the password obviously;
https://gyazo.com/15b67e6030d6b697488fb75bcdbab9dd

This is the JDBC database connection string (password removed from it);
jdbc:mysql://u2_w1us4b8NrX:mypassword@myserverip:3306/s2_TotalEconomy

What am I doing wrong? Thank you.

**Comment by Erigitic** [comment]
This one should work, not sure why it isn't:

```
database {
    enable=true
    password="mypassword"
    url="mysql://158.69.121.39:3306/s2_TotalEconomy"
    user="u2_w1us4b8NrX"
}
```

Could it potentially not allow connections to the database from wherever you're running the server from? Also, could you send me the full log file?

By the way, I removed the link to your gist as I believe one of the url's still contained a password, so please check that out.

**Comment by itzrobotix** [comment]
I have other plugins hooked into other SQL Databases just fine and also thanks for removing the link, the password will be changed now but I must have missed that one. Is it at all possible, there was an ‘@‘ in the password. Could that cause issues with the url?
The only error it gives is to check the credentials which I can see is the message thrown from the UncheckedExecutionException. So I can only assume it’s an issue with my credentials and the only possible thing anyone has been able to suggest is the fact there was an @ in the previous password. Haven’t tried it without yet but plan to on next server restart, could this be the issue? 

Thanks for your quick response by the way!

**Comment by itzrobotix** [comment]
UPDATE: The password having an "@" symbol in it was causing the connection issue, it managed to connect to the database but now it's having another issue that's kind of related.
Seems it's unable to create the tables in the database or something, here is the stacktrace;
https://pastebin.com/Tt89k62S
Any idea what is causing this issue? @Erigitic

**Comment by Erigitic** [comment]
I'll take note of the issue with the `@` in the password. I'm sure the way the password is being passed into the string is incorrect in the code, and should be an easy fix.
