### ISSUE TITLE
Money Cap

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#45]

**Comment by SnowBlitzz** [comment]
bump :p

**Comment by MarkL4YG** [comment]
@SnowBlitzz I guess I know why you bumped this, but please specify your idea/suggestion as there're many different ways of realizing a money cap

**Comment by Erigitic** [comment]
@SnowBlitzz I have been really bad at updating the plugin but I still have plans to add this. If you have anything in particular that you would like to be added let me know. Otherwise I will just add in a money cap that can be set and enabled/disabled from the config.

**Comment by SnowBlitzz** [comment]
Ah sorry about that. Just thought maybe this got lost and forgotten. I was thinking of a configurable money cap which when the player reaches that amount wont add anymore. Example if I reach 999,999, i cant earn more than that or gain more than that, it will just stay 999,999.

**Comment by MarkL4YG** [comment]
I think a cap for money/day,month,hour,minute,... would also be a nice idea :)
Could be implemented using the "per time" value of "-1" for a total money cap and 0 for no cap, so both systems would be possible with one solution and maybe even groups
