### ISSUE TITLE
Use IDs for job rewardables instead of names

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#46]
Currently jobs use the name of a block/item/mob in order to determine how much exp/money a player gets from it. This prevents jobs from working with mods in most cases. So a switch to IDs would make jobs compatible with most, if not all, mods.

**Comment by Erigitic** [comment]
So the Minecraft block names look like this: "minecraft:block_name". Anyone know the format for modded block names?

**Comment by MarkL4YG** [comment]
Having searched a bit I say that there's no guideline that tells a mod/plugin dev how to structure their unlocalized block/item names.

But just in case you didn't already know this: Commonly ``<modID>(.<subType(s)>).<blockName>'`` seems to be used. (Most mods base themselves on vanilla which works more or less.)

Also: I think using IDs is not the solution here:
In my opinion you can just give the admin a config where he/she can simply edit what blocks are used in what job.
This way would allow the exclusion of items/blocks/... too.
For configurations with a high number of jobs you may also include a possibility for block-groups in that config. This would allow multiple jobs to share some of the blocks without having to have the names in the config twice.
