### ISSUE TITLE
Developer API Improvements

### ISSUE THREAD

**Issue by Flibio** [Erigitic/TotalEconomy#5]
I was looking into using your developer API for a plugin, and realized that it simply is not powerful enough to do what I wish to do. I have a few suggestions:

- Instead of passing a Player object to the API, use a UUID. It is easier for developers to use and is more powerful

- Have a few more methods available to use, such as setting a player's balance and registering a new player

**Comment by Erigitic** [comment]
I will get to work on this today. Thanks for the suggestion.

**Comment by Erigitic** [comment]
Just finished the switch from Player objects to UUID's. I will release it soon. Thanks again for the suggestion.

**Comment by Flibio** [comment]
No problem!
