### ISSUE TITLE
Chest Shops

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#50]
Chest shops will utilize a custom inventory instead of the actual chest's inventory as this will prevent others from "pumping" items out of the shop. The only thing we have to worry about is making sure that when the inventory is destroyed, the items are returned to the player's inventory, or dropped on the floor if not enough slots are available. 

As well as that, item lore is being used to store the buy/sell price and the quantity of items for sale. Though, it may be better to just use the stack size of the item instead of the lore for the quantity. 

Lastly, items will be able to be purchased by left clicking the item in the shop and sold by right clicking the item. A shop owner will be able to decide if they want to only sell, only buy, or both sell and buy an item.

**Comment by MichaelFedora** [comment]
I would personally leave this to another plugin, but that's up to you guys.

**Comment by MarkL4YG** [comment]
I think both would be a good idea:
Command/ui based shops could be used not only to buy items, but also to run commands (e.g. for renting/buying a special service or whatever you may also have in mind).

ChestShops offer the possibility to sell items to normal users <-> UI wouldn't

**Comment by SnowBlitzz** [comment]
Hmm for an economy plugin I think this is not needed. Maybe you're already convinced of adding this but there are separate plugins that has this feature and some people who use economy plugins don't necessarily use admin shops. Pixelmon has its own npc shopkeepers for example

**Comment by Erigitic** [comment]
Everything in Total Economy can be enabled/disabled to the server owners liking. So if they do not want to deal with shops or they would rather use a different shop plugin then they can disable Total Economy's version of shops and use the other one with no issues whatsoever.

**Comment by SnowBlitzz** [comment]
Ah I see, being able to enable/disable them would be a good choice if you're planning to implement things branching out of the idea of an economy plugin :+1:

**Comment by ResqDiver1317** [comment]
Chest Shops and Sign Shops would be great features. All of our bukkit/spigots servers on our community use them both. I personally was never a fan of the command/UI based shop style, but I know it def has it's place. 
 Would it also be a possibility (i apologize if this is already in the works and I missed it somewhere) to have a "shop rental or purchase" feature? With Spigot, we use AreaShop for that. As admins, we define regions for each shop and set a price, then players can rent that shop space for a set price/duration then setup their shop inside that region. If they do not renew their rent, then the region gets reset so the next person can rent it. This would allow there to be a "Mall" that so players looking to buy stuff dont' have to go all over the map to find chest shops. All of the shops are in 1 place and a player simply has to browse the different shops in the mall for what they want to buy.

**Comment by MarkL4YG** [comment]
Signshops most often are just admin chestshops ^^ I guess that would be a good feature to start with

**Comment by Erigitic** [comment]
@ResqDiver1317 I do like the idea of renting a shop or at the very minimum having region based shops. This is definitely a possible addition to Total Economy that we'll keep in mind when work begins on it. Thanks for the suggestion, it's greatly appreciated!

**Comment by smmmadden** [comment]
Are there more documents on the shop features, permissions and setup, configuration files, etc?
I was able to point at a chest I put down and type in /shop buy
But this is what I get: Message not found (en): command.shop.buy.success
And then trying to stock a chest with chests, I typed in: /shop stock 1024 10 with the chests in hand.  I had 64 in hand, and it went to the chest but not the 1024.  Guess it can only put what you're holding?
Again the game reported: Message not found (en): command.shop.stock.success

I think it would be better to simply say **Shop Purchased for $10** (or other default cost) and when the stocking is good "Shop Stocked with 1024 Chests".  State the quantity and the item being stocked.  That would be more user-friendly.

I'm using the 1.8.0 version with Sponge 2958 and Forge 2615 for Minecraft 1.12.2 and my Pokemon Revival world.  I thought there was a separate shop config file but not seeing anything getting created.
Thanks!

**Comment by MarkL4YG** [comment]
Did you update TE? You may need to delete your messages file so TE can update it.

**Comment by smmmadden** [comment]
Thanks - I did update from the 1.7 version to the 1.8.0 but thought the mod would have updated the config files.  I renamed it and the latest version was created.
Messages for both commands now reflect the right messages.

Two follow on questions:
1. Are you going to be updating the [main page](https://ore.spongepowered.org/Erigitic/Total-Economy) with the Chest Shop instructions ?
2. I was able to stock a chest successfully, but clicking with left button I was unable to purchase the item in the chest. How can I test if the shop works if I cannot buy from it?

Thanks!

**Comment by Erigitic** [comment]
I do plan on adding documentation on Chest Shops to the Ore page soon. 

Do you get any console errors or messages when you left click an item in the shop?

**Comment by smmmadden** [comment]
nothing without the debugging turned on for LuckPerms, but with verbose and left-clicking I see:
![image](https://user-images.githubusercontent.com/10309346/37404428-3a5d288a-2768-11e8-9190-f4fdbed03c1e.png)

everything looks okay from the above since nothing appears to be missing from totaleconomy perms or would otherwise not allow me to purchase from my own chest shop.

**Comment by Erigitic** [comment]
Would you mind making a separate issue for this? Please include Total Economy, Sponge, and Forge versions there as well.

**Comment by smmmadden** [comment]
don't mind at all - will get one created asap and yes that is correct with the API's.  Too bad they are not compatible if that's the problem

**Comment by ResqDiver1317** [comment]
Is there any possibility of getting (or if it exists where can I find it) of getting the updated version that has the shops and such for API5? many servers are still using modpacks made for 1.10.2 and it would be nice to have the great features included. If not, I understand, but it would be nice to have if possible.

**Comment by Erigitic** [comment]
@ResqDiver1317 This could be a possibility. Please make a separate issue for this so it can be discussed further. Thanks.
