### ISSUE TITLE
Can not view balance of offline players.

### ISSUE THREAD

**Issue by Rentai** [Erigitic/TotalEconomy#52]
https://i.gyazo.com/27b72c6842b4fbde749cdda19ce35304.png

**Comment by Erigitic** [comment]
Yeah this was actually intended as I had no way to test if it worked on my end and I planned on coming back to it to make this work. I will look into this and get it working. Thanks.

**Comment by Erigitic** [comment]
I found a really easy fix for this and will release the update tomorrow. If you are interested you can check out the change here: https://github.com/Erigitic/TotalEconomy/commit/0368992f717e96d9446c35154702ff672d21a11c
