### ISSUE TITLE
[Suggestion] Firms / Companies

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#56]
( Could be linked to #35 )

Create companies (and accounts for them), pay employees (maybe even at different salaries), maybe even automatically take orders.

I think it's clear what I'm thinking abount ^^

**Comment by Erigitic** [comment]
Closing this as I feel it would be better implemented by a standalone plugin.

**Comment by MarkL4YG** [comment]
I think this would have to wait at least until the new economy API.
