### ISSUE TITLE
Balance not updating

### ISSUE THREAD

**Issue by Flibio** [Erigitic/TotalEconomy#6]
I am using TotalEconomy's API to add currency to a player's balance. It successfully adds the currency(It updates in the accounts file), but when I run /balance the currency hasn't changed at all. ~~When I restart the server, it changes the balance in the accounts file back to what it was when using /balance.~~ The only way that I can get the balance to update is by restarting the server.

**Comment by Erigitic** [comment]
Ok. Let me go ahead and test this out on my end and I will get back to you in a little bit.

**Comment by Erigitic** [comment]
Just recreated the issue. I will try to get it fixed today. Thanks for bringing this up.

**Comment by Flibio** [comment]
Ok thanks

**Comment by Erigitic** [comment]
Ok I figured it out and will release it later today once I fix up a few more things. Thanks again for bringing this up.

**Comment by Erigitic** [comment]
Here is the fix: https://github.com/Erigitic/TotalEconomy/releases/tag/v1.0.8. Please get back to me when you test it just so I can make sure it is working for you as well.

**Comment by Flibio** [comment]
Everything seems to be working, I will let you know if I find anymore bugs

**Comment by Erigitic** [comment]
Glad to hear.
