### ISSUE TITLE
Admin Shop

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#69]
The idea of the admin shop is that a command will be run such as "/shop" and a custom inventory will open up where players can purchase/sell items. I am planning on this being customized from a config file. Customization includes shop title, shop items, item prices, and whether or not items can be both sold and bought or just sold or bought. And just like every feature, shops can be enabled/disabled from the main Total Economy configuration file.
- [ ] Configuration Creation
- [ ] Configuration Loading
- [ ] Custom Inventory
- [ ] Mechanics

**Comment by SnowBlitzz** [comment]
Description?

**Comment by Erigitic** [comment]
Working on it. Just added it here as a reminder. Give me time :smiley:

**Comment by Erigitic** [comment]
Waiting on some more API implementation before adding this.

**Comment by Erigitic** [comment]
https://github.com/Erigitic/TotalEconomy/issues/50
