### ISSUE TITLE
1.0.6 - 1.0.8 Errors

### ISSUE THREAD

**Issue by paleym** [Erigitic/TotalEconomy#7]
Working on a new server: Sponge 1.8-1499-2.1DEV-553

Plugins:
SpongeEssentialCmds-2.0
permissionsex-sponge-2.0SNAPSHOT
TotalEconomy (trying out versions to find what one works for this sponge build)

I get errors upon launch for all versions 1.0.4 and up, but the errors for 1.0.5, 1.0.6, 1.0.7, and 1.0.8 all say that the totaleconomy verison is 1.0.5?

1.0.5 crashlog pastebin: http://pastebin.com/UFYkVkSc
1.0.6 crashlog pastebin: http://pastebin.com/UdV8X41f
1.0.7 crashlog pastebin: http://pastebin.com/SeNSJy05

I was wondering if the download links are wrong or if not, and which is the right version for my build.  Thank you!

**Comment by Erigitic** [comment]
Update to Java 8
