### ISSUE TITLE
/vbal tab

### ISSUE THREAD

**Issue by SnowBlitzz** [Erigitic/TotalEconomy#71]
/vbal tab shows ALL the players who've logged in the server and putting the first letter of name then tab shows ALL players with username starting that letter. Would it be possible to only show the one's online?

**Comment by Erigitic** [comment]
The view balance command was recently changed to allow for viewing of all users balances, including offline ones. So even if I could change this I do not think I would as it would ruin the point of the command itself.

**Comment by SnowBlitzz** [comment]
Yeah, but I mean, you can manually input the player's name /vbal SnowBlitzz if you wanna see his balance when he's offline but when you enter /vbal then tab, all of the players pop up. Limit it to just pop up the online users and keep the offline balance checking

**Comment by Erigitic** [comment]
If this can be done I don't think it would be an easy implementation. I can't seem to find any information on it.

**Comment by MarkL4YG** [comment]
Wasn't it previously like this ? Simple solution could be reusing the old implementation and creating an argument like "[online|offline]" or even just adding another command ?
