### ISSUE TITLE
[Suggestion] /apay - admin pay, gives player a money from console

### ISSUE THREAD

**Issue by doozzik** [Erigitic/TotalEconomy#73]
I am using CustomNPC mod and it will be nice to allow NPCs to increase player balance after completing the quest, by using command "apay @p 100".

**Comment by Erigitic** [comment]
I am glad you brought this up as someone was asking about a command to remove money, might have been you, but I did not see the reason for it. But now that you bring up custom NPCs giving out money I completely understand the use for this. So thanks.

Anyways, I will add this and it may be as easy as updating the "pay" command. If not I will just add a new command. Thanks for suggesting this.

**Comment by MarkL4YG** [comment]
@doozzik just a side note: You know that <code>@p</code> is the alias for "nearest player" and that this could cause issues if another player is closer to the NPC ?

**Comment by doozzik** [comment]
Yes. I hope, players wouldnt cheat :)
