### ISSUE TITLE
Ability to reload configuration files without restarting server

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#74]
I believe this is made possible/a lot easier with version 4.1.0 of the Sponge API. Not sure if it will work but I will give it a shot.

**Comment by MarkL4YG** [comment]
Sounds good, would help you if needed

**Comment by Erigitic** [comment]
The plan here is to allow everything BUT features to be reloaded. Making it so features can be reloaded might cause quite the headache as well as performance issues the way things are currently setup. Might work on changing this later, but at the moment it makes sense to require the server to be restarted to enable/disable features. I am going to change the config files around a bit to make it clear as to what can/can't be reloaded. So everything within the main, totaleconomy.conf, config file will not be able to be reloaded. Other then that I am hoping everything else can be changed and reloaded with ease.

And just so I remember, sponge has a command built in the will run the GameReloadEvent which is "/sponge plugins reload".
