### ISSUE TITLE
[Suggestion] Default 'job'notifications' setting

### ISSUE THREAD

**Issue by WryWolfy** [Erigitic/TotalEconomy#77]
As the title suggests, I think it'd be useful if there were a way to set the default status of 'jobnotifications' for players - to "false" instead of "true" - in the totaleconomy.conf.  So when a new player logs in and is registered into the accounts, then the 'jobnotifications' would be set to "false" by default - the player would have to use the '/job toggle' command to enable the notifications.

Thanks for your time,
~ WryWolfy

**Comment by MarkL4YG** [comment]
Sorry for double reference, first commit included changes that weren't supposed to be committed #derp
 
However, this is now implemented and tested against the latest SpongeAPI from GitHub (4.2.0-SNAPSHOT) using SpongeForge in my Fork.

**Comment by WryWolfy** [comment]
Sweet!  Thanks for jumping on it!  Hope it's merged as well.

**Comment by Erigitic** [comment]
Submit a pull request, make sure it is in the develop branch, and I will gladly get this merged. Thanks for the help!
