### ISSUE TITLE
Fast gain (bug)

### ISSUE THREAD

**Issue by LawlyPopz** [Erigitic/TotalEconomy#84]
in 1.8.9 you can plant and chop and replant saplings without them growing also if u silktouch ores u can place them down and re silktouch to gain money and exp

also /balancetop doesnt not work

**Comment by Erigitic** [comment]
The saplings are a part of the Lumberjack job. You can remove them from the jobs config file. Also, Total Economy has a config setting that prevents the sort of "farming" that you are talking about where someone can place and mine ore over and over again. This can be turned on by setting "preventJobFarming" to true in the Jobs config file. All this does is destroy the ore without dropping anything to prevent players from constantly placing and breaking. Lastly, balance top is only present in the latest version, 1.5.0-DEV, of Total Economy.
