### ISSUE TITLE
[1.10.2] Pay Command - Error

### ISSUE THREAD

**Issue by Rasgnarok** [Erigitic/TotalEconomy#88]
Running `TotalEconomy-1.5.1.jar` and `spongeforge-1.10.2-2073-5.0.0-BETA-1683.jar ` with `Forge 2073`, and I have an error message every time that someone does the /pay command.

https://gyazo.com/c67b14d53eee180e8d102989c3405902

**Comment by MarkL4YG** [comment]
uhm, you know that (according to [gh releases](https://github.com/Erigitic/TotalEconomy/releases)) the lastest pre-release is just 1.5.0 ? ._.

**Comment by Erigitic** [comment]
@Rasgnarok Did you just rename the file or is it a typo?

**Comment by Rasgnarok** [comment]
Aha, typo yep. thanks for catching that <<

**Comment by Erigitic** [comment]
Let me test this on my end and I will get back to you. Thanks.

**Comment by Erigitic** [comment]
I was not able to recreate the issue. Try again on the latest version of forge and sponge. If it still happens then wait till the full release of 1.5.0 as it could just be an issue with the DEV version.

**Comment by Erigitic** [comment]
@Rasgnarok Are you still having this issue on the latest version of Total Economy?
