### ISSUE TITLE
[1.10.2] Error with jobs and block break

### ISSUE THREAD

**Issue by mister-man** [Erigitic/TotalEconomy#89]
Hallo together,

I found an error with the job system. If eg. the miner, mines ores, there a lot of block braking errors in my console whem preventJobFarming=true !

Thanks

**Comment by Erigitic** [comment]
I will take a look into this. Thanks.

**Comment by Erigitic** [comment]
This has been fixed and will be released with v1.5.0. Thanks for posting this.
