### ISSUE TITLE
baltop not working. [1.8.9]

### ISSUE THREAD

**Issue by IBGnova** [Erigitic/TotalEconomy#92]
Hello,
So I updated to version 1.5.0, and it seems /baltop is tossing an error and not wanting to work at all. I have tried restarting my server, and using fresh configs, but nothing has worked. 

This is the error it is giving: Error occurred while executing command: No value present. 

I am using pixelmon 4.2.7, The latest 1.8.9 sponge forge version, and the latest 1.8.9 forge version.

**Comment by MarkL4YG** [comment]
Please provide a full log using
[hastebin.com](http://hastebin.com) or
[pastebin](http://pastebin.com)

**Comment by Erigitic** [comment]
@IBGnova Please provide an error log or we will assume it has been fixed. Thanks.

**Comment by IBGnova** [comment]
Oh, I forgot about this. Yeah I assume the issue was because the plugin is meant to be for 1.10, and I was trying to run it on 1.8.9.
